### ISSUE TITLE
Open Web Fellows - Emailing All Applicants

### ISSUE THREAD

**Issue by DaveSteer** [MozillaFoundation/movement-building#1]
Starting a project to upload all of the applicants into an email tool so that we can inform them of the status of their application. Ideally, we can send this email week of 1/12.

Note on Privacy: We cannot email these people ongoing since ongoing communication is not the nature of why they gave us their email address. We should invite them to sign up to stay up to date though.

cc @valianttry and @Kellijk

**Comment by valianttry** [comment]
@DaveSteer what email tool are you using?

**Comment by DaveSteer** [comment]
I'm not using any tool. Right now, the only thing I have is our corporate GMAIL, which seems like the wrong thing to use. I suppose we could put all 573 applicants in the BCC line, but that doesn't seem right, does it?

**Comment by davidascher** [comment]
Given that this is a one-time thing, I think it's important not to overthink it.

Gmail may balk at 573 people in a bcc, but if it works, it's probably the easiest for you.

two alternatives based on tools we understand well in-house:
- setup a BSD group (@valiantry can help I'm sure!)
- setup a mailing list just for this (#servicenow or @jlin can probably set it up quickly too).

**Comment by Kellijk** [comment]
Hi @DaveSteer! Sorry - just now seeing this, had my Github training today :)

David's definitely right here. Given it's a one time thing I'd recommend not creating a BSD constituent group, but if you feel strongly about it I can make it happen. Also there are ways to do it via gmail where you can add personalization (like first name), I've done this a bunch of times: http://neworganizing.com/contentblog/update-gmail-mail-merge

I'm not worried about 500 bcc or being marked as spam, as long this is a one-off thing and it's not something that will happen often.

Dave let me know if there is anything else I can do to help out with this.

**Comment by DaveSteer** [comment]
Sounds good. Melissa Romaine is going to reach out to you on this. @melechuga
