### ISSUE TITLE
Complete design work on Call Congress tool

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/movement-building#10]
To-do
- [x] initial screen mobile UI
- [x] second screen mobile UI
- [x] design 'preview' experience
- [x] double check most recent sandstone styles
- [x] get copy review / edits
- [x] get signoff from andrea
- [x] design QA for the build
- [x] initial screen desktop UI
- [x] second screen desktop UI
- [x] error states
- [x] design thank you page, mobile
- [x] design thank you page, desktop

_Moved P2 tasks here: #15_

~~P2:~~
~~design report back, mobile~~
~~design report back, desktop~~
~~build p2 QA~~

**Comment by cassiemc** [comment]
This is great, thanks for breaking up the tickets. Most recent designs are here: https://redpen.io/mjd5f98ae0b751ab15 I have an R+ from @vazquez, so just need an R? from @valianttry and copy review. 

@OpenMatt who should I ping for copy review?

**Comment by valianttry** [comment]
@cassiemc I have the final language as approved by legal for the disclaimer:

"Your call is connected with the help of a company called Twilio. In order to connect you with your correct elected official in the U.S. Congress and with the FCC, Twilio asks for your zip code. Twilio also collects your phone number to connect your call. This information will be stored for no more than 30 days, and will not be used for any other purposes. For more information, see Twilio's privacy policy."

"Twilio's privacy policy" should be linked to: https://www.twilio.com/legal/privacy

**Comment by cassiemc** [comment]
Perfect, thanks! Updated the mocks: https://redpen.io/mjd5f98ae0b751ab15 Need to update w/ the logo though.

**Comment by cassiemc** [comment]
Ok, here's the design with the updated footer. @valianttry do you want to do a final sign-off? https://redpen.io/mjd5f98ae0b751ab15

@edrushka @OpenMatt @HPaulJohnson Do any of you have time to do a quick copy review? We can adjust any changes in the build.

I'm going to move on to desktop screens asap. cc @ScottDowne

**Comment by edrushka** [comment]
@cassiemc This is really nice work! The entire experience seems very clear. Added some minor copy suggestions in the pad, but overall R+ on copy.

**Comment by HPaulJohnson** [comment]
Looks awesome, can't wait to call my congress person with it! Left a few comments in the redpen.

**Comment by cassiemc** [comment]
Desktop versions coming here: https://redpen.io/gs2b3baa91abfb01ff
Feedback @vazquez @flukeout if you guys have a sec.

**Comment by valianttry** [comment]
@cassiemc  I shared the designs with Holmes Wilson at Fight for the Future and he had some good feedback (take what's useful, but i know we're crunched for time and can't go through umpteen iterations):

Those designs look great. 

Also, the one thing I’d flag is that the page is a bit too tall for the call form to be visible in an average person’s browser window without scrolling. We’ve found that makes a huge difference. Also many users have the default mac dock, toolbars, etc which reduce the height of their screen. Within 500px from the top is usually the goal for us, ideally.

Being able to see the button makes it instantly clear what the user is being asked to do, and they can’t quite tell if they have to read and scroll. We see conversion drop off a lot when the button is “below the fold” even though supposedly “folds” are a thing of the past :)

If the designs here are different options I think the second one puts the call form highest and is very readable.

Two other specific options / suggestions would be to:

1) Find a way to get the “36 days” to appear in line with “The FCC votes on net neutrality in” on typical Macbook screens. 

2) Go with this design for the call form http://grab.by/Ejdw but incorporate “Enter your phone number to get started.” at the end of the short paragraph of text, in bold perhaps. That reduces the number of elements in the form and the heigh of the form while making it clear what’s being asked for. 

Let me know if there’s a ticket I should post these to. I didn’t want to just come from out of nowhere with a bunch of unsolicited advice :)

Anway, this is great. Totally on the right track. This will be huge.

**Comment by valianttry** [comment]
One quick note on this process:
I think not knowing what comes _before_ and _after_ this experience puts the designer at a disadvantage. For advocacy it's really important to know where the audience is coming from and therefore how they've been "prepped" before they see a tool like this. (This is a note for me as well to be more forthcoming with that context for you in future design projects.) In this case, the audience is a smallish, US-only segment of people we are targeting because they have already signed our net neutrality petition OR they are Mozilla employees or dedicated volunteers. For example, most of them are going to get an email that looks like this (ignore the yellow highlight):

![Call Congress Email](http://note.io/18CslVH)

**Comment by davidascher** [comment]
+1 on having the user's context explicit up-front in the design process.
Good point @valianttry

**Comment by OpenMatt** [comment]
@cassiemc  is the design work complete or ongoing?

**Comment by cassiemc** [comment]
Sounds like there could be another round of feedback incorporated if that suits @ScottDowne's timelines. And we need to design the 'report back' feature.

**Comment by cassiemc** [comment]
- Most up-to-date mobile designs are here: https://redpen.io/mjd5f98ae0b751ab15
- Most up-to-date desktop designs are here: https://redpen.io/gs2b3baa91abfb01ff
- @valianttry – I _really_ appreciate the full context of the experience, thanks! It's pretty much what you described, and I like to design for people not reading a bunch of text in an email, but it is definitely helpful. Also helpful was the other feedback – I'm sure we'll discuss in a minute, but just wanted to show you the button on the desktop homepage is right at that 500px line. We can easily bring it up above the line by reducing some paddings/margins, but the text is also readable now: https://redpen.io/rne1eb49cb4ed26297

**Comment by cassiemc** [comment]
My new to-do list:
- [x] Thank you screen (desktop). Wires here: http://note.io/1z8jUXh and here: https://sendto.mozilla.org/page/content/FCCvote-net-neutrality-share
- [x] Thank you screen (mobile)
- [x] Upload final mobile screens: https://redpen.io/mjd5f98ae0b751ab15
- [x] Upload final desktop screens: https://redpen.io/gs2b3baa91abfb01ff
- [x] design QA for the build

P2, if there's time:
- [ ] design report back, mobile
- [ ] design report back, desktop
- [ ] build p2 QA

**Comment by cassiemc** [comment]
Posted the final designs, @alicoding @valianttry @simonwex @jdotpz (see checklist above).
Will work on 'report back' next.

**Comment by cassiemc** [comment]
@valianttry @simonwex I can't find the original wireframes anywhere in this quamire of issues! I'm looking specifically for the 'report back' page, do either of you have that handy???

**Comment by cassiemc** [comment]
For my reference:  
Test site here: https://mozilla.github.io/call-congress-net-neutrality/
File boogs: https://github.com/mozilla/call-congress-net-neutrality/issues

**Comment by cassiemc** [comment]
If there are no objections I am going to file the 'Report back' designs as additional issues and close this one out. So that I can feel good about myself. :)

**Comment by cassiemc** [comment]
P2 issues for Report Back filed here: #15
