### ISSUE TITLE
Add Google Analytics to call Congress tool 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/movement-building#11]
Add Google Analytics, pageview and event tracking.

Related issues for reference: 
- Complete DESIGN work on Call Congress tool #10 
- Complete DEV work on Call Congress tool #9

**Comment by ScottDowne** [comment]
This is the repo I have been using up to this point: https://github.com/ScottDowne/call-congress-net-neutrality

**Comment by adamlofting** [comment]
@ScottDowne @simonwex or @jdotpz :
- [x] Which domain (or subdomain) are the call congress _HTML pages_ being hosted on? (we need this to setup GA, especially if it's something new) [confirmed call.m.o]
- [x] Who is hosting the server side bit of the call-congress tool?

@valianttry : 
- [x] Are we running any optimization testing? (is there any plan to run this like EOY for example) [confirmed no optimization on page, just at snippet level]
- [x] What events other than standard pageviews do we want to count? (I guess survey completions... any others?)

**Comment by jdotpz** [comment]
_Who is hosting the server side bit of the call-congress tool?_
That would be us.

**Comment by jdotpz** [comment]
We're considering using the mozillafoundation.org domain.  I'd ask @simonwex and @valianttry to please help us decide on a subdomain for this.  Some ideas...

call.mozillafoundation.org
Actually, I think that's the best option.  Remember, we'll use this tool for many campaigns, so I am loathe to call it callcongress., since sometimes, like this time, it's actually calling the FCC.  Thoughts?  We need to hurry and decide, too.  SSL sometimes takes a bit!

I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1129466 to get DNS moved over with some haste.

**Comment by adamlofting** [comment]
Thanks for the update @jdotpz 

Is the HTML / front-end going to be hosted at the same location? Or is the call.tbc... domain just where we host the service. @ScottDowne do you have any clues based on the current build process? 

For setting up Google Analytics, I need to know the domain for the front end pages, especially if it's a mozilla.org subdomain as I'm not an admin there and it can mean a couple of days turn around. 

The same goes if we're using a new domains (technically the MoCo SLA is 14 business days to turn these around, and that team is busy right now).

**Comment by jdotpz** [comment]
The update to the update is that we're using call.mozilla.org @adamlofting and that appears to be finalized at this point.  

The HTML/Front end Are hosted in S3/Cloudfront, while the API backend is a classic autoscaling infrastructure setup.

**Comment by adamlofting** [comment]
Great! The request is now open to setup a new GA property which we can use with this domain. https://bugzilla.mozilla.org/show_bug.cgi?id=1129929

**Comment by valianttry** [comment]
I just flagged gareth cull who runs google analytics to see if he can speed up this bug. @adamlofting

**Comment by adamlofting** [comment]
@simonwex @alicoding 

We're ready to add Google Analytics to this now. 
- [x] We need to add this to the master template (or each page):

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49796218-17', 'auto');
  ga('send', 'pageview');

</script>
```
- [x] We need to include this [webmaker-analytics](https://github.com/mozilla/webmaker-analytics) module whichever way is best suited to the way this app is built. 
- [x] We need to instrument the javascript interactions we want to measure which do not generate new pageviews. If the action simulates a new page, but doesn't change the URL, we fire `analytics.virtualPageview(...)`, or if it's an in-page event we use `analytics.event(...)` - [documentation here](https://github.com/mozilla/webmaker-analytics)

```
analytics.virtualPageview('preview-the-call-script');
etc...
```

I can't walk through all the screens here without a US phone number, but the key screens are when someone starts the process, and finishes the process.

**Comment by alicoding** [comment]
@adamlofting I have done three of the checklist here and have PR up https://github.com/mozilla/call-congress-net-neutrality/pull/52 for review

**Comment by adamlofting** [comment]
Thanks @alicoding :+1: 
I can confirm these events are coming through to Google Analytics now. :smile:
