### ISSUE TITLE
What data will help us plan advocacy strategy in 2015?

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#12]
We want to analyze our email list, and our online advocacy data to share with participants in the advocacy work week Feb 12 - 18. We need to list some key questions we'd like answered (with data) that will help us map the most effective strategy and goals. 
@Kellijk @DaveSteer

**Comment by valianttry** [comment]
**Basic List Management Qs:**
- How big is the list now? What has the rate of growth been?
- What campaigns have contributed to that growth? By how much?
- What is our organic growth rate?
- What's our deliver-ability rate?
- What is our unsubscribe rate?
- What's our average open rate? How has segmentation impacted open, CTR, response; etc?
- How do the ^ metrics compare to other nonprofits or analogue groups?
- How have ^ metrics improved / worsened in response to segmentation?

**Responsiveness:**
- What issues get the highest response? What segments respond best to which issues? Least to which issues? (e.g. Webmaker group response to net neutrality)
- Do signers have an impact on responsiveness?

**Digging Deeper:**
- Where do we see progress in improving our key list metrics? Where are opportunities to improve in 2015?
- What do we have to do to maintain the rate of growth?

**Localization:**
- How can we begin to incorporate more localization into our online advocacy program? Are there locales where we could start? 
- How can we leverage L10N?

**_What else @Kellijk @DaveSteer @adamlofting ?**_

**Comment by adamlofting** [comment]
`Basic List Management Qs`
- Where do organic signups happen? (e.g. is this mozilla.org)

`Responsiveness`
- How do organic signups compare in responsiveness vs people who signed up on a particular issue (this is a challenge for any nonprofit working on many issues)

Other "data" if we had it would be 
- What do our advocates care about, and want to see us work on
- What are our advocates willing to to (depth of engagement)
- Maybe we could survey the people who have signed a petition in the last 12 months

**Comment by cassiemc** [comment]
@adamlofting @valianttry can we close this?

**Comment by adamlofting** [comment]
:+1:
