### ISSUE TITLE
Remove zipcode from call-congress api app

### ISSUE THREAD

**Issue by jdotpz** [MozillaFoundation/movement-building#14]
Per https://github.com/mozilla/call-congress-net-neutrality/issues/3#issuecomment-73213689 we would like to remove zip codes from the call logs in the call-congress backend application ( https://github.com/mozilla/call-congress )

**Comment by valianttry** [comment]
@jdotpz did this get done? Mind closing 'er up if 'yes'?

**Comment by simonwex** [comment]
This didn't get completed, but with our low data-retention policy, I'm happy closing as good.
