### ISSUE TITLE
Design 'Report Back' for Call Congress

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#15]
Moving the second design phase into this ticket, from #10. 
- [ ] design report back, mobile
- [ ] design report back, desktop
- [ ] build p2 QA

**Comment by valianttry** [comment]
Hi there! Any update on when the designs might move forward on the report back? There are 15days left in the campaign, so just checking in. We will be sending an email to the foundation list asking people to call the week of the 16th. It would be great to have the report back functionality in place by then. Note that it does NOT have to be beautiful or technical, the function is much more important than the form. Thanks!

@simonwex @OpenMatt @cassiemc @ScottDowne

**Comment by cassiemc** [comment]
I have another p1 for the rest of this heartbeat but could move on this next week. @valianttry, can you paste the original wireframe here for that report back page? Maybe the guys could start building it off of that and I can go back and with a design review when I have more cycles.

**Comment by valianttry** [comment]
Cool, I can't figure out how to attach a PDF, but below is a very rough outline for what the survey would look like. Note that we should not collect anything other than responses (no IP address, email; etc) since we just want to see aggregate data, and give people a chance to offer written feedback. The data could even be stored in a Google Doc (nothing fancy needed):

![call_tool_screenshots](https://cloud.githubusercontent.com/assets/9830371/6135586/cba84fd6-b11e-11e4-80ae-6cd6df34e014.png)

**Comment by ScottDowne** [comment]
I have been working on these on a p2 basis and getting feedback from Ricardo when needed.

![mobile](https://cloud.githubusercontent.com/assets/197334/6135600/0f4e122a-b138-11e4-8046-b4e2c3e6eee4.png)
![tablet](https://cloud.githubusercontent.com/assets/197334/6135603/140391dc-b138-11e4-9782-ee3614fded7c.png)
![fullscreen](https://cloud.githubusercontent.com/assets/197334/6135605/17401b18-b138-11e4-952e-e1006de5767e.png)

**Comment by ScottDowne** [comment]
This is a WIP but it's in HTML and CSS already.

@valianttry yeah, it was my intent as well to submit this to a google doc.

**Comment by valianttry** [comment]
oh awesome! you folks are amazeballs. My only input is that people are connected with all FCC members in sequence (not just one) which makes the survey tricky. See my treatment -- saying "at least one" is a hack, but i'm open to suggestions.

**Comment by valianttry** [comment]
Also, people should only be able to choose 1 option (i see multiple checks in some of these)
