### ISSUE TITLE
Social share graphics for Celebration outreach on February 26th - 27th

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#16]
Etherpad here:

https://foundation.etherpad.mozilla.org/NN-victory-social

@iamjessklein @cassiemc @simonwex

**Comment by edrushka** [comment]
Hey @iamjessklein when can we expect a mockup? Please let me know if there are any blockers. Thanks!

**Comment by edrushka** [comment]
@iamjessklein @cassiemc We're expecting the FCC's decision by 10:00 am ET Thursday so we've got a pretty tight timeline. Can you deliver a mockup today so the team can give feedback?

**Comment by iamjessklein** [comment]
Hey @edrushka @cassiemc @valianttry - we are in a work week - sorry for the silence. We hope to get something to you to look at later today.

cc/ @sabrinang

**Comment by iamjessklein** [comment]
We are exploring a facebook and twitter social share. @edrushka @valianttry Do you have the copy finalized?

Here are a few options that I'm thinking of:
- update this Washington graphic below to add balloons, streamers etc - to show that we are celebrating a victory.
- show some sort of celebration
- have bold text saying "I protect the world's largest public resource" #wewontheweb or some variation of that.

Reference graphic: 

![screen shot 2015-02-24 at 12 38 46 pm](https://cloud.githubusercontent.com/assets/535012/6355221/66257350-bc22-11e4-9ee3-fe6a0aa4a3af.png)

**Comment by valianttry** [comment]
-- I really like option #3 since I think it'll be more "sharable" -- meme-ish. 
-- Could we also have a celebratory version of the "I helped protect the world's largest public resource"  / #wontheinternet img as a Facebook profile image? I'd love to swap my image out that day, and others might also like that option.
-- It would also be nice to have an updated "announcement" type graphic that has some streamers / horns; etc to announce the "win" that we also send from @mozilla channels. I think it's fine to recycle the Capitol Building graphic for that purpose, but it's also cool to rif or go into a different direction.
Here are a few copy directions (these are also going to be tweeted from #Firefox):
- Today, the FCC voted to protect #netneutrality. YOU made this victory possible. You #wontheinternet!
- The FCC’s vote on #netneutrality today is victory for the world’s largest public resource: the Web. 
- Today's FCC vote is a big victory! Thanks for your help protecting the world’s largest public resource: the Web. 
- Victory for #NetNeutrality! Thanks for your calls and actions to protect the world’s largest public resource: the Web. You #wontheinternet today.

**Comment by edrushka** [comment]
cc @kevzawacki @HPaulJohnson

**Comment by iamjessklein** [comment]
I made some graphics - [please drop feedback in redpen](https://redpen.io/p/xz3dcd0aa97ea663a1)
I tried to keep to the palette already created for Net Neutrality campaigns. 

![drib-revisions](https://cloud.githubusercontent.com/assets/535012/6369825/c56e5076-bcb7-11e4-9d68-b480e3828dc4.png)

![celebrity-05](https://cloud.githubusercontent.com/assets/535012/6369383/e4a70824-bcb3-11e4-842e-838f49cd7b71.png)

![emailer-new](https://cloud.githubusercontent.com/assets/535012/6369255/6194eac4-bcb2-11e4-97bd-f3d1182b85bd.png)

cc/ @kevzawacki @hpauljohnson @edrushka @sabrinang @valianttry @cassiemc

**Comment by valianttry** [comment]
@Kellijk

**Comment by iamjessklein** [comment]
Revisions up on [Redpen](https://redpen.io/ty1e9e8e8bb2648050):
![rednn-01](https://cloud.githubusercontent.com/assets/535012/6379701/3b7bd744-bd02-11e4-8164-ef86f6fcdb99.png)
![fireworks](https://cloud.githubusercontent.com/assets/535012/6379702/3d6b28ca-bd02-11e4-8379-f3d174625124.png)

**Comment by valianttry** [comment]
All look good -- I have a strong preference for the red!
For the personal profile photo -- can we try something even more "badge-ey" and readable, like this: http://note.io/1MSlJlU (only not slapped together in Keynote)

**Comment by valianttry** [comment]
@iamjessklein if you could prioritize the simplified Facebook profile image that would help us a lot. We're linking it in our email, which Kelli has in production. We also have to test it prior to tomorrow's launch.

**Comment by iamjessklein** [comment]
![finals](https://cloud.githubusercontent.com/assets/535012/6383697/642d2fe8-bd21-11e4-9f9f-740bf65aeb00.png)

Added to dropbox [here](https://www.dropbox.com/sh/5j9bun6w066sz6m/AAAvT7mFZ2jHv1MkJmVxMVeaa?dl=0)

**Comment by valianttry** [comment]
@jdotpz see ^ for the dropbox files. @Kellijk FYI

**Comment by jdotpz** [comment]
Filenames, all sitting on wewon.mozilla.org/filename
facebook.png                fb.png                        twitter-fireworks.png
fb-avatar.png                nn.ai                        twitter.png
fb-fireworks.png        twitter-avatar.png
