### ISSUE TITLE
Solve: How to offer download of Facebook celebration image for 2/26 NN victory?

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#17]
@iamjessklein @simonwex @cassiemc 
Hopefully Jess has time to create a Facebook profile image for people to swap in on celebration day Thursday / Friday #16 . How can we offer it to folks, say in a link in an email, to download the image so they can swap it in for their Facebook image? 

Referral campaign from HRC profile image campaign: http://www.hrc.org/viral

**Comment by valianttry** [comment]
Here is the email draft we want to launch to 1.5 million on Thursday offering the image to use on their Facebook profile: https://docs.google.com/a/mozillafoundation.org/document/d/1kjyfq4kic41QLmRsbPVMiN_MXOQBxpszxHfCZmQwdVk/edit

**Comment by simonwex** [comment]
@jdotpz do we have a cloud-fronted bucket that we can use for this?

**Comment by jdotpz** [comment]
We could use stuff.webmaker.org but we can easily make a new bucket, named whatever you'd like, and hook it up to something on mofoprod.net or with MoCo's support, something under mozillafoundation.org ?

**Comment by valianttry** [comment]
obviously we want it to be easy -- maybe "wewon.mozilla.org" or something like that? Webmaker isn't a brand connected directly to the campaign, so I'd use a different one. I admit I may not fully understand the Q.

**Comment by Kellijk** [comment]
heyyo @jdotpz  - either of those sound great to me, I don't have strong feelings about the actual URL, just want to make sure we're able present the graphics in a way that look solid, so we should go forth with whatever will look the best and is easier to get together.

**Comment by jdotpz** [comment]
We don't care about SSL on this, do we?  cc @simonwex 
I've got d2bgn2xfie6516.cloudfront.net created from the wewon.mozilla.org bucket, and I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1136894 to setup DNS to that.  @valianttry @simonwex @Kellijk let me know who will need to upload to this bucket.

**Comment by valianttry** [comment]
@iamjessklein primarily, she's designing the assets

**Comment by jdotpz** [comment]
Excellent.  As soon as we have DNS setup, I'll hook @iamjessklein with the ability to update that image.

**Comment by jdotpz** [comment]
Note: these are crappy res screenshots to use in the example email, do not use these for prod!  
http://wewon.mozilla.org/eg1.JPG
http://wewon.mozilla.org/eg2.JPG
http://wewon.mozilla.org/eg3.JPG
http://wewon.mozilla.org/eg4.JPG
http://wewon.mozilla.org/eg5.JPG

**Comment by iamjessklein** [comment]
Hey - I put the files on dropbox [here](https://www.dropbox.com/sh/5j9bun6w066sz6m/AAAvT7mFZ2jHv1MkJmVxMVeaa?dl=0)
