### ISSUE TITLE
Delete phone numbers and other data as promised for call tool users

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#19]
We promise to delete call data associated with users within 30 days. We can do this anytime, but should complete it no later than March 15.

@simonwex I assigned JP (guessed)

**Comment by jdotpz** [comment]
We already delete this nightly.

**Comment by simonwex** [comment]
:rocket: :rabbit: !

**Comment by valianttry** [comment]
^ WHAT WEX SAID! :boom:
