### ISSUE TITLE
Design update to advocacy site for fellows announcement

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/movement-building#20]
Meta ticket is here: https://github.com/MozillaFoundation/plan/issues/370
Driver: @edrushka
Design: @iamjessklein 
Decision-maker: @Melechuga
Consulted: @DaveSteer  @valianttry @KevZawacki @HPaulJohnson 

Deadline for design: May 22
### Next steps

[x] Scope work (done [here](https://foundation.etherpad.mozilla.org/open-web-fellows-site-updates))
[x] Design fellows banner on front page 
[ ] Design fellows page (the page the front page banner links to) 
[ [ Get final approval from decision-maker on both of those
[ ] Pass off to Ali to build (Issue #21)

**Comment by edrushka** [comment]
@iamjessklein did some great work rethinking the structure of the advocacy site to carve out space for promotional content. We still need to scope the fellows update, but pasting Jess' designs as inspiration: https://redpen.io/ov9f35d39b5ecbe2ee

**Comment by Melechuga** [comment]
Specs:
- 6 Fellows, going to 6 host organizations.
- Story: Meet our first cohort of fantastic Fellows! (We're treating them as one cohort, and not focusing on the 6 individual stories as much.)
  Need: 
- Announcement that goes on the front page (advocacy.mozilla.org) and lead to the "Open Web Fellows" page (https://advocacy.mozilla.org/open-web-fellows/) 
- Designs for Fellows page with space for photos + profiles; space to highlight the host organizations.

**Comment by KevZawacki** [comment]
Any background documents I'll need to start in on the copy? Or, should I simply draw on this: https://advocacy.mozilla.org/open-web-fellows/

**Comment by iamjessklein** [comment]
also don't feel compelled to use my design work - was just sketching

**Comment by edrushka** [comment]
@iamjessklein here's the work @flukeout is doing to replace the Net Neutrality take action banner with the success banner: https://github.com/MozillaFoundation/plan/issues/399

**Comment by iamjessklein** [comment]
thanks
@Melechuga @edrushka @DaveSteer can you tell me what the name of the program is? Google - Mozilla Open Web Fellows?

**Comment by Melechuga** [comment]
@iamjessklein Ford-Mozilla Open Web Fellows. Website: https://advocacy.mozilla.org/open-web-fellows/

**Comment by Melechuga** [comment]
@KevZawacki We have some other documents that could be more useful for wording; I'll ping them to you via email.

**Comment by iamjessklein** [comment]
I put some sketches up. Please add your feedback [to the redpen](https://redpen.io/p/todce5900fd1e6f214)

**Comment by iamjessklein** [comment]
@edrushka updated with placeholder art mockups

**Comment by iamjessklein** [comment]
Updated both the Open Fellows and Surveillance content. 
Take a look and comment on redpen [here](https://redpen.io/cx15d88f7f19121420) and [here](https://redpen.io/ahefee82bb2ef994e0)

cc/ @edrushka @valianttry @OpenMatt @Melechuga @DaveSteer @KevZawacki @ScottDowne 

![advocacy-1](https://cloud.githubusercontent.com/assets/535012/7006987/b76d0f88-dc53-11e4-97ef-f775e49a07c3.png)

**Comment by iamjessklein** [comment]
New mockup to correspond with the snippet and tile campaign imagery (but the Open Web Fellows remain untouched).
In order to implement this, I will need:
- [ ] photos of fellows
- [ ] final copy 

![takeaction](https://cloud.githubusercontent.com/assets/535012/7026199/5df661b6-dd16-11e4-8e45-fb7efb9c7ee1.png)

**Comment by OpenMatt** [comment]
Thanks Jess. Looks great to me. @Melechuga: you're the decision-maker. Does this design work for you on the Open Web Fellows piece?

**Comment by OpenMatt** [comment]
### Need fellow photos

@Melechuga : we also need finalized photos for the Fellows. so that Jess can add them into the design. Do you have those?

**Comment by OpenMatt** [comment]
### Need 2015 fellows page copy
- @Melechuga : we also need copy for the "meet the fellows" page. Presumably with short bios for each of the Fellows. @Melechuga @KevZawacki do you have that? 
- We can follow a similar format to what Open News does here:  http://opennews.org/what/fellowships/2015meet/

**Note this means we'll have _two_ pages:**
-  i) https://advocacy.mozilla.org/open-web-fellows/ -- with information about the fellowship _in general_. and 
- ii) a new page.  " https://advocacy.mozilla.org/open-web-fellows/2015 " -- where we get information about the 2015 fellows specifically, with their photos and bios. Similar to how Open News does it. 
- Here's a mock-up showing how the sub nav would work: https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/fng8sjb8.png 

@Melechuga : sound good?

**Comment by Melechuga** [comment]
Thanks @iamjessklein! Looks great. 
At the moment, copy + photos are still TBD; if you could please finish the design with dummy content that would be great. Have talked to @OpenMatt; he has details for going forward.

**Comment by KevZawacki** [comment]
@Melechuga @OpenMatt 

Draft copy for pages 1 and 2 is here: http://goo.gl/kFmW0S
Awaiting @Melechuga & @DaveSteer's approval, plus details on the individual fellows.

**Comment by Melechuga** [comment]
Thanks @KevZawacki! Made a few suggestions using language from our program overview (https://docs.google.com/a/mozillafoundation.org/document/d/1mhRtRkQORvRQbodehJJzQ_ypbovzdyxQe-layvftjvc/edit#) for the first paragraph. Awaiting @DaveSteer's review. Fellow details will come at a later date.

**Comment by OpenMatt** [comment]
@KevZawacki looks great -- on page 1  I'd just change "FORD-MOZILLA OPEN WEB FELLOWS" to FORD-MOZILLA OPEN WEB FELLOWSHIPS
- so: page 1 is about the Fellowship. page 2 is about the Fellows.

**Comment by OpenMatt** [comment]
@iamjessklein if you're able to create this as a dummy page in WordPress, that'll make it easy for others to just flow in the new copy and bios when they have them. @Melechuga if you can make sure Jess has the WordPress credentials she needs that would probably help.

**Comment by DaveSteer** [comment]
Sending @iamjessklein the credentials to the wordpress site now.

**Comment by iamjessklein** [comment]
Update: You can [check the redpen](https://redpen.io/oydebbe556026f6c07), but I iterated a little on the eye design. 
![advocacy-plaineye](https://cloud.githubusercontent.com/assets/535012/7053213/5fff577e-de01-11e4-96e7-7b9d3465ba87.png)
