### ISSUE TITLE
Build update to advocacy site for fellows announcement

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/movement-building#21]
Meta ticket is here: MozillaFoundation/plan#370
Driver: @edrushka
Dev: @alicoding 
Decision-maker: @Melechuga 
Consulted: @DaveSteer @valianttry @KevZawacki @HPaulJohnson 

Scoping document: https://foundation.etherpad.mozilla.org/open-web-fellows-site-updates

We need to:
- [ ] Build the design finalized in Issue #20
- [ ] QA on staging
- [ ] Push to prod at Kevin/Melissa/Dave's discretion

Deadline: Needs to be ready to go live by June 3

**Comment by Melechuga** [comment]
Want to see if we can add one small link to the header on the front page when this goes through; no design needed, just add a link (Community) to our external discourse page from the front advocacy.m.o page. Thanks!

**Comment by edrushka** [comment]
I'm not clear where this link should go.

**Comment by Melechuga** [comment]
We're thinking after "Open Web Fellows" but before "Get Involved," and it would link to https://discourse.mozilla-advocacy.org/

![screen shot 2015-04-02 at 2 05 19 pm](https://cloud.githubusercontent.com/assets/5815317/6973690/5b257702-d941-11e4-8d78-5fb62711ca7c.png)

**Comment by edrushka** [comment]
Ah, I see: another link in the top nav. That should be possible. Thanks for clarifying.

**Comment by alicoding** [comment]
Can I request someone who got admin permission to create me user account on https://advocacy.mozilla.org ?

**Comment by edrushka** [comment]
Done.
