### ISSUE TITLE
Create section 215 petition page 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/movement-building#25]
- Full context is in the Planning meta-ticket:
  https://github.com/MozillaFoundation/plan/issues/426
- We'll use the exact same template as the Net Neutrality petition page:
  https://sendto.mozilla.org/page/s/FCCvote-net-neutrality
- Finalized copy for the page is here (it has been reviewed and approved by legal, policy) http://mzl.la/1NL2OsJ
- Remove the "countdown" feature we used for NN. It's not needed here.

**Comment by OpenMatt** [comment]
Question for @valianttry. Do you want to:
a) Remove the countdown?
b) Keep it. And have it say "Section 215 of the Patriot Act Expires in X days," with countdown to June 1?

**Comment by valianttry** [comment]
@OpenMatt 

The language has been reviewed and approved by legal, policy; etc. Final  language is here:

https://docs.google.com/a/mozillafoundation.org/document/d/16jQ79yjCAC76Q88JZDePVQcy8iyA8JVSnzTyVmsDg2U/edit

Still need:
- Opt-in language
- Security, Privacy review

**Comment by OpenMatt** [comment]
Awesome! now that the language is approved, all blockers are clear on this ticket. We should be able to press ahead with the dev work. We just need a dev assigned -- as per my flag for @simonwex and @davidascher here:
https://github.com/MozillaFoundation/plan/issues/426

**Comment by valianttry** [comment]
Let's remove the countdown at the top alltogether, it's not as "clear cut" of an "end date" as for the net neutrality vote. Congress could just kick the can again and render June 1 moot.

**Comment by OpenMatt** [comment]
- Assigning to @ScottDowne  as per Wex
- Scott: can you confirm here that you have what you need to get started?

**Comment by ScottDowne** [comment]
Dev page: https://sendto.mozilla.org/page/s/section-215-petition-dev

Ready for QA and when that's done I can update the url and it should be good to go.

**Comment by ScottDowne** [comment]
I stubbed out a thank you page: https://sendto.mozilla.org/page/s/section-215-petition-thanks

Not sure what we want in it yet.

**Comment by OpenMatt** [comment]
@ScottDowne : remove double period here. "Tell Congress to stop bulk collection of our personal information.."

**Comment by OpenMatt** [comment]
@ScottDowne can you include a link to the thank you page we used for the Net Neutrality petition? We can adapt what we did there here.

**Comment by ScottDowne** [comment]
Here is the NN thank you page: https://sendto.mozilla.org/page/s/FCCvote-net-neutrality-thanks

**Comment by OpenMatt** [comment]
Thanks Scott. @valianttry : can you advise on whether you'd like to follow the same or different approach on the thank you page? Plus any copy changes you'd like?

Do we want to to include the Call Congress tool here, or just remove it and include the email sign-up prompt?

**Comment by ScottDowne** [comment]
@valianttry so, I'm having issues getting the signature to actually go somewhere... Not sure what I am missing yet.

**Comment by ScottDowne** [comment]
From: http://tools.bluestatedigital.com/kb/article/how-is-constituent-data-updated

"When records, new or existing, enter your constituent system, they are temporarily staged.  Matching, merging, and conversion to a permanent constituent record is handled by a timed process.  For that reason, you may experience a delay of 15-30 minutes from the time a record enters your system to the time that new information becomes available for your use."

That might be my issue...

**Comment by OpenMatt** [comment]
@ScottDowne is that a question for Andrea? or for engineering / @simonwex / @jbuck ?

**Comment by ScottDowne** [comment]
@OpenMatt It's for someone that knows BSD. I think my page is setup wrong, but I'm super stumped.

**Comment by ScottDowne** [comment]
I updated the link: https://sendto.mozilla.org/page/s/section-215-petition

Still not accepting submissions though. Still stumped.

**Comment by OpenMatt** [comment]
re: thankyou page: @valianttry sends this:
the confirmation page should not include the call Congress promotion at this time. I marked it up here:
![sendto_mozilla_org___2015_fccvote_net_neutrality_thanks](https://cloud.githubusercontent.com/assets/9830371/7015059/84c7500a-dc82-11e4-89cb-feccf1f6acd9.png)

**Comment by OpenMatt** [comment]
@wex or @jbuck : @ScottDowne needs help with BSD issues here. can you help?

**Comment by ScottDowne** [comment]
Fixed it: https://sendto.mozilla.org/page/s/section-215-petition

Properly storing submissions now. I emailed BSD help yesterday and they got back to me today.

I'm sorting out the thank you page, shouldn't be long now.

**Comment by ScottDowne** [comment]
An email is sent right now when a user signs up on the thank you page.

Should I continue to send this or remove the sending feature? I say we should send an email.

Right now I borrowed the email from net neutrality, which has a generic "... Thank you so much for signing up to get important news and information from Mozilla. ..." email body (I didn't paste the wole email), and a title of "Thanks for helping protect net neutrality"

@valianttry @OpenMatt We should change that title to something else? Thoughts?

**Comment by ScottDowne** [comment]
Net neutrality thank you page sign up redirected to this: https://sendto.mozilla.org/page/content/FCCvote-net-neutrality-share

So I created a: https://sendto.mozilla.org/page/content/section-215-petition-share/

I need to update the contents in the share messages, they are still net neutrality:

I'm not sure how, but I'll likely need copy for that too. Net neutrality ones are like so:

![share](https://cloud.githubusercontent.com/assets/197334/7029307/c8a04108-dd2a-11e4-996f-abffdb16ff64.png)

@valianttry @OpenMatt thoughts on share content copy?

**Comment by OpenMatt** [comment]
@valianttry : can you provide confirmation email copy? + share message copy?

**Comment by OpenMatt** [comment]
@davidascher @wex : we're pretty close to having this completed and ready to ship. What's the protocol / next steps for testing and QA on petition pages like this?

**Comment by OpenMatt** [comment]
@KevZawacki : Andrea says you can provide the confirmation email and share message copy, above. Doable? Those are now the final blockers on this one.

**Comment by KevZawacki** [comment]
@OpenMatt @valianttry 

Certainly. How's this:

Share copy:
- Twitter: I just signed the petition to end mass surveillance. Tell Congress how you feel about Section 215: [link]
- FB: You can help end mass surveillance. Sign the petition to Congress and help put an end to Section 215, legislation that threatens privacy and the open web. [link] 

Confirmation email copy:
- Subject: Thank you for standing up to mass surveillance 
- Body: Thanks for standing with Mozilla and protesting the government's bulk collection of personal information. In speaking out against Section 215, you're championing an open, free and healthy Web. We'll stay in touch and share updates about Section 215, which Congress is slated to vote on before the end of spring. In the meantime, sign and share our petition [link] to let Congress know: it’s time to stop mass surveillance.

**Comment by ScottDowne** [comment]
@KevZawacki I think this is a generic signup email in the post process. So it probably shouldn't be about section 215 but about mozilla in general, no?

The page that sends the email is here: https://sendto.mozilla.org/page/s/section-215-petition-thanks

**Comment by ScottDowne** [comment]
@KevZawacki However, we are not currently sending out an email for 215 signatures, and we can! If so that email copy can be used.

I can do that but it wasn't the original question and up to this point I wasn't aware that we wanted that.

**Comment by KevZawacki** [comment]
@ScottDowne Ah, pardon the confusion — my fault. Scott, are you able to share the full copy from the original net neutrality email? I can use that as a springboard.

**Comment by ScottDowne** [comment]
@KevZawacki Original net neutrality didn't have an email, only the thank you page sent out an email, and it had a specific name and a generic body. The body was as follows:

```
Hi there, 

Thank you so much for signing up to get important news and information from Mozilla. Email helps us connect to people like you who care about building and protecting an open Web. We value your time and attention, so we try to only send you messages that matter, and keep the inbox clutter to a minimum. 

Stay tuned — we'll be sending you important news about campaigns, events, and opportunities to get involved. 

Together, we will keep the Internet open, accessible, transparent and safe. 

Sincerely,

Mark Surman
Executive Director
Mozilla Foundation

P.S. Mozilla is a non-profit and we rely on donations and grants. If you'd like to support our mission to build and protect an open web, please click here to make a secure online donation today: https://sendto.mozilla.org/page/contribute/givenow-seq. Thanks!
```

I think we can get away with keeping it the same if possible.

**Comment by valianttry** [comment]
Yes please don't change standard copy that's not dated. We don't send a confirmation after someone takes action (feels spammy). We only send confirmation if someone signs up to be on our list. Let's not create more work than needed :)

@KevZawacki re: share copy i offer minor tweaks. I wouldn't say 215 specifically because no one knows what it is, i'd keep it to "mass surveillance".

Share copy hacks:

```
Twitter: I just signed @Mozilla's petition asking Congress to end mass surveillance. Please join me - take action now and RT: [link]
FB: I just did my part to end mass surveillance. Join me and sign @Mozilla's petition to Congress right now b/c keeping us safe shouldn’t cost us our privacy: [link]
```

**Comment by KevZawacki** [comment]
+1 to @valianttry's revisions. Thanks!

**Comment by valianttry** [comment]
@ScottDowne When will you be ready for Q&A? Lemme know. I have a few little things like this: 

![sendto_mozilla_org___section_215_petition](https://cloud.githubusercontent.com/assets/9830371/7034394/f501e3ae-dd35-11e4-9404-e32d0faab2e2.png)

**Comment by ScottDowne** [comment]
@valianttry now is good

**Comment by ScottDowne** [comment]
Updated the copy and updated the email subject title.

I just need to figure out how to embed the social sharing links with updated copy.

**Comment by ScottDowne** [comment]
Share page is done.

I think that was everything requested in this ticket?

QA?

**Comment by OpenMatt** [comment]
What's the final step to close this ticket? @ScottDowne: are we waiting on @valianttry for final QA?

**Comment by OpenMatt** [comment]
@valianttry : please give final approval here so we can close this ticket today.

**Comment by OpenMatt** [comment]
will close this one once that padding issue is resolved

**Comment by valianttry** [comment]
I just tested the petition again and got the old social share copy again from NN, is that because i need to do a hard refresh? I tested in both FF and chrome
![facebook](https://cloud.githubusercontent.com/assets/9830371/7120897/7b93fd60-e1c5-11e4-8109-3c2a84f90243.png)

**Comment by ScottDowne** [comment]
@valianttry I'll double check.

**Comment by ScottDowne** [comment]
@valianttry Good catch. Should be fixed now.

What was wrong was the new thank you page was redirecting to the old share page.

I updated the link in one spot, but that wasn't enough, I needed to update it in the code too.

**Comment by mmmavis** [comment]
sometimes using the [Facebook Debugger](https://developers.facebook.com/tools/debug/) to fetch new scrape info would help

**Comment by valianttry** [comment]
Yup fixed. We really need to make our social share prettier than the giant M I made 1.5 years ago in PPT :wink: Not today obvi.

**Comment by ScottDowne** [comment]
Pretty sure this should be closed.

Page is live here: https://sendto.mozilla.org/page/s/section-215-petition

If there are other bits that we are waiting on, they can be filed in more specific tickets.
