### ISSUE TITLE
Update advocacy.mozilla.org frontpage

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/movement-building#26]
- Context in Planning meta-ticket: https://github.com/MozillaFoundation/plan/issues/426
- Goal: update the front page of the site with a "Sign the section 215 petition" call to action. Similar to what we did with the Net Neutrality campaign. 
- Master design file http://mzl.la/1CfzhPh more context: http://mzl.la/1NEAx5g 

There's a dependency here that will need some co-ordination: @iamjessklein is already working on updates to the site. To announce the Open Web Fellows. So @iamjessklein: we'll need to co-ordinate.
- Meta ticket for the open web fellows work: https://github.com/MozillaFoundation/plan/issues/370#issuecomment-88281231
- Design ticket: https://github.com/MozillaFoundation/movement-building/issues/20

**Comment by OpenMatt** [comment]
Jess is already working on updates to the page to announce the Open Web Fellows. Here's her Redpen: https://redpen.io/dxd5f78746d8c15c63
- @valianttry : I think we should be able to just paste your new copy + a link into her existing design. The icon at the left (Congress with the red background) could work as is. we can just remove the fireworks.
- @valianttry : let us know here when you have some copy ready?

**Comment by valianttry** [comment]
@OpenMatt so close, got feedback from policy team on draft.  Final text coming (possibly) tomorrow.

**Comment by iamjessklein** [comment]
Great @valianttry @OpenMatt I will have mockups to share on Monday.

**Comment by OpenMatt** [comment]
Note the new mock-ups here: 
https://redpen.io/cx15d88f7f19121420
https://redpen.io/ahefee82bb2ef994e0

**Comment by OpenMatt** [comment]
@iamjessklein is the only difference here the red binoculars vs. white binoculars?

**Comment by OpenMatt** [comment]
@valianttry : let us know if you have finalized copy that Jess can flow in here for your piece?

**Comment by valianttry** [comment]
Final petition copy is here: https://docs.google.com/a/mozillafoundation.org/document/d/16jQ79yjCAC76Q88JZDePVQcy8iyA8JVSnzTyVmsDg2U/edit 

This copy can be used for anything (short descriptions; etc)

**Comment by OpenMatt** [comment]
@iamjessklein when you're done the design work for this, will up need help from a developer to implement?

**Comment by iamjessklein** [comment]
Updated design can be found [on redpen](https://redpen.io/myb3ad380c9196493d) 
![takeaction](https://cloud.githubusercontent.com/assets/535012/7025434/9f817e4a-dd11-11e4-8770-4ff2bce7718f.png)

**Comment by iamjessklein** [comment]
For quick implementation, I'd recommend first doing a quick change to the Net Neutrality work with this CTA, and then circling back later when we have the Open Web Fellows work finalized. 

cc/ @Melechuga @OpenMatt @valianttry @ScottDowne

**Comment by OpenMatt** [comment]
@iamjessklein looks great Jess. I'm still not clear though: 
 once this new design is approved and ready to ship, will you need a developer to implement it? Or can you implement the changes on production yourself?

**Comment by OpenMatt** [comment]
@valianttry can you sign off on the surveillance portion of the new design? copy and graphic look good to you?

**Comment by OpenMatt** [comment]
@valianttry : please sign off and then we can mark this one closed.

**Comment by OpenMatt** [comment]
The design for this is done. But will wait to mark this closed once it's shipped to the live site. @iamjessklein : do you need a developer to do that? Or can you do it?

**Comment by ScottDowne** [comment]
I'm doing dev for this right? If so, I'm happy to just do the dev in this ticket.

**Comment by iamjessklein** [comment]
Thanks @ScottDowne - is there anything that you need from me to help you move forward?

**Comment by OpenMatt** [comment]
- This links to the petition page, so is naturally blocked on sec review closing first.
- Note that we're only shipping the Surveillance CTA, not the web fellows portion: https://dl.dropboxusercontent.com/spa/6c38yp3crbxni5b/cp2ad2cm.png

**Comment by OpenMatt** [comment]
@ScottDowne : you all set to push this to prod once the petition page is live?

**Comment by ScottDowne** [comment]
@OpenMatt nope, just starting dev on it now.

**Comment by ScottDowne** [comment]
![front-eye](https://cloud.githubusercontent.com/assets/197334/7122821/d034392c-e1eb-11e4-8087-f99159852362.png)

Not sure how to share this live because it's bsd, but here is a screenshot.

Here is the code: http://pastebin.com/ZhDiFcq8

Pasting that into advocacy homepage call to action, and hitting preview, should get you the page we can publish when ready.

**Comment by edrushka** [comment]
Hey @ScottDowne - can we make this live as early as possible tomorrow (April 14)? The petition goes live tomorrow morning, and it links to this page. Please flag @valianttry for review on Skype or IRC when it's up, since we can't really see it on staging. Thanks!

**Comment by ScottDowne** [comment]
@edrushka can do. How does 9:00 EST sound?

**Comment by ScottDowne** [comment]
Actually, would rather ship 6:00 EST if it's all the same to everyone else.

@valianttry @DaveSteer Sound good?

**Comment by ScottDowne** [comment]
It's up. https://advocacy.mozilla.org/

Now that it's live, iterating on new issues becomes much easier.

**Comment by iamjessklein** [comment]
Since this is up, I propose that we close this issue. Any additional issues should be filed separately. :bug: :beetle: 

cc/ @OpenMatt @edrushka

**Comment by ScottDowne** [comment]
@iamjessklein agreed, closing.
