### ISSUE TITLE
Develop messaging for Net Neutrality Advocacy Campaign

### ISSUE THREAD

**Issue by DaveSteer** [MozillaFoundation/movement-building#3]
This is the issue to create the messaging for the Net Neutrality Advocacy Campaign. We need approved messaging by January 15th. We need to consult with the MoCo engagement team. Need messaging for:
*Petition landing page
*Short form call to action for snippet, social, etc.

Here's the Google Doc for the messaging: https://docs.google.com/a/mozilla.com/document/d/1P-AAaD3TJSmJXmuwObIE51Qrl7ftdApiioE2cSuGOW4/edit?usp=sharing

@valianttry @Kellijk @HPaulJohnson @edrushka @chriswryly

**Comment by valianttry** [comment]
Other messaging drafts underway:

Mozilla Foundation email series:
https://docs.google.com/a/mozillafoundation.org/document/d/18zJefpaJq0-8RxySXghHxXosxyLH2UkrwdnGs_P8RtQ/edit

Firefox & You Email Copy Draft:
https://docs.google.com/a/mozillafoundation.org/document/d/1PC8ZKQ-ifwUW3gz06Nvb0W03uHB7My4EqtPCwaKMNWw/edit

Draft Blog Post by Dave:
https://docs.google.com/a/mozillafoundation.org/document/d/1q4GFju0e5CR4jyxMPhYLKAHy_XB6NJvFHEacIqu9DYk/edit
