### ISSUE TITLE
Design tile for section 215 petition campaign

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/movement-building#33]
- Planning ticket: https://github.com/MozillaFoundation/plan/issues/426
- Specs: http://mzl.la/1FES7nV

**Comment by OpenMatt** [comment]
Initial copy ideas: (static / rollover)

Stand up to mass surveillance / Petition Congress to end Section 215
Tell Congress it's time to stop mass surveillance / Sign the petition to end Section 215
You can help stop mass surveillance / Tell Congress not to reauthorize Section 215
Protect your right to privacy / Take action now to stop Section 215
Congress votes soon on mass surveillance / Stand up now and sign the petition
Sign the petition to end mass surveillance / Tell Congress how you feel
Stand up for your privacy / Sign the petition to end mass surveillance

**Comment by OpenMatt** [comment]
@valianttry says:

I don't think we should say "section 215" in any of our shorter calls to action, it's not recognizable / jargon. We should just say "help end mass surveillance". I also don't like "Tell congress how you feel" -- it sounds wishy-washy and not impactful. I like this one best:

Tell Congress it's time to end mass surveillance / Sign the petition

if the above is too long:

It's time to end mass surveillance / Sign the petition

**Comment by OpenMatt** [comment]
### Finalized copy for tile

@iamjessklein :
here is our finalized copy:

**Tell Congress it's time to end mass surveillance / Sign the petition**

or if the above is too long:
**It's time to end mass surveillance / Sign the petition**

@iamjessklein can you proceed and close this out?

**Comment by iamjessklein** [comment]
Hey I took a stab at a few options for the tile direction. Please add your comments on [redpen](https://redpen.io/ob285439f46e2e0f5e)

![tile-options](https://cloud.githubusercontent.com/assets/535012/7068861/5967cdb8-dea3-11e4-8c14-8a7ef957e40d.png)

**Comment by OpenMatt** [comment]
nice! over to @valianttry : for approval.

**Comment by valianttry** [comment]
I like all of them! Can we make "Sign the Petition" under the eyeball a little bit larger font? It looks smaller than the others. Other than that, these are all approved! Thanks so much @iamjessklein

**Comment by iamjessklein** [comment]
Revised [on redpen](https://redpen.io/fc8c046f4ad156fb45)

![tiles-export](https://cloud.githubusercontent.com/assets/535012/7077370/3cf3f8e2-dede-11e4-8667-e89dc208fc5d.png)

**Comment by iamjessklein** [comment]
Or.... 

![output_yr5cdi](https://cloud.githubusercontent.com/assets/535012/7077930/de015172-dee2-11e4-8634-ced119ce3f9c.gif)

![sign](https://cloud.githubusercontent.com/assets/535012/7077967/0b4067e0-dee3-11e4-880d-46437519ad6e.png)

**Comment by OpenMatt** [comment]
@valianttry : can you give final approval here today and then close this ticket?

**Comment by iamjessklein** [comment]
I believe @valianttry said that she was going to share this with the corporation folks. Is it possible to get a final decision or for me to do an art handoff today?

**Comment by OpenMatt** [comment]
@valianttry: what's the status on this one?

**Comment by valianttry** [comment]
Tiles are not launching tomorrow. We're working with Moco on 1) finalizing the promotion schedule / audience; and 2) getting their feedback on design. This might be on hold for the moment. 

So @OpenMatt nothing is holding anything up from your end... it's other stuff being worked through.

**Comment by valianttry** [comment]
Potential updated copy:
Option 1:
static state: What does the US government know about you?
hover: Get smart on mass surveillance

Option 2: Are you under surveillance?
hover: Find out what the US government knows

Option 3: Should the US government collect data about everyone?
hover: Get smart on mass surveillance

**Comment by edrushka** [comment]
I vote option 1. My alternative would be:
static state: Is the US government watching you?
hover: Get smart on mass surveillance

**Comment by valianttry** [comment]
+1 let's go with that copy

**Comment by edrushka** [comment]
@valianttry so for design shall we update the blue eyeball with the
 new eyeball design?

**Comment by cassiemc** [comment]
@iamjessklein can you update the blue tile with a white version of the new eye? Here are the svg assets: https://www.dropbox.com/sh/tlifkldxcuqokzn/AAAp1yw-FEQFY5_wv1wHPBhxa?dl=0

**Comment by iamjessklein** [comment]
@cassiemc is the thought here that the image of the eyeball would remain static for the tile?

**Comment by cassiemc** [comment]
No, it would work just like the snippet, just with the updated style of the eye.

**Comment by iamjessklein** [comment]
So I'm just going to update the mockup, and someone will code that interaction, right?

**Comment by cassiemc** [comment]
Yes :)

**Comment by ScottDowne** [comment]
What is the current target release date for this?

Has there ever been an interactive tile before? Do we have permission and the ability to do this?

Is it just html/css/js in a tile? <- that might be a question for myself.

**Comment by iamjessklein** [comment]
@ScottDowne - If it's not "tracking the cursor" this could be a CSS animation or gif. 

@valianttry @edrushka do you know the answer to Scott's questions above? 

also - should the copy be maintained?

**Comment by iamjessklein** [comment]
Here are two iterations for the tile: 

1) [Matches the original design:](https://redpen.io/vb0998fed07e448eea)
![tiles-blue](https://cloud.githubusercontent.com/assets/535012/7493216/c718c450-f3cc-11e4-80de-f35ae9720ab2.png)

2) [Aligns with the current design:](https://redpen.io/pc71b718b36ee06ef6)
![tiles-matching](https://cloud.githubusercontent.com/assets/535012/7493219/cda6a03a-f3cc-11e4-97d6-c153f810f081.png)

**Comment by cassiemc** [comment]
Thanks @iamjessklein! Left some feedback in the redpens.

**Comment by ScottDowne** [comment]
Looking at a bunch of existing tiles, it seems our options are images or gifs, it looks like one large clickable button, and we can have two images (if we want) on for hover and one for not.

Today I need to find someone who knows better, but I suspect the above limits are our limits.

**Comment by ScottDowne** [comment]
The specs for tiles are in the first comment, I missed this initially.

**Comment by iamjessklein** [comment]
I updated the [Redpens](https://redpen.io/qweabb09d71739961e) and designs:

![tiles-grid](https://cloud.githubusercontent.com/assets/535012/7495419/cc67485a-f3db-11e4-80fa-a8b853855cce.png)

![tile-options](https://cloud.githubusercontent.com/assets/535012/7495425/d4b24686-f3db-11e4-9496-1296cfe24f0e.png)

**Comment by valianttry** [comment]
@iamjessklein can we plug in the updated text from https://github.com/MozillaFoundation/movement-building/issues/33#issuecomment-99137274?

**Comment by iamjessklein** [comment]
Before I iterate, can you please confirm:

a) copy: 
- static: " Is the US government watching you?
- hover: Get smart on mass surveillance

b) which design should we move forward with? (My preference is the blue eye without the box (bottom left in the comment above.)

**Comment by valianttry** [comment]
Thanks for the work on this!

blue eye is fine, yes, that's the correct copy.  If we can wrap this soon that would be great (we're losing signatures  because we could be in Tile but are on hold until this design is finalized).

**Comment by iamjessklein** [comment]
Two options:

![front-backwithred](https://cloud.githubusercontent.com/assets/535012/7501265/cac6b2e0-f400-11e4-9d3a-b4cd2aea0da7.png)

-or -

![front-backwithtan](https://cloud.githubusercontent.com/assets/535012/7501272/d103cfa8-f400-11e4-8733-7098f3aa5784.png)

my preference = red.

**Comment by edrushka** [comment]
Nice! Do we know yet if there will be eyeball tracking? If not, perhaps the pupil should be in the same place in the eye in both states, so the hover will create an iris dilating effect.

**Comment by cassiemc** [comment]
I also like the red. "g" in "Get" should be capitalized. Pupil seems like it should be a bit bigger to me too, but this change is not a blocker.
﻿
![icon-eye-pupil](https://cloud.githubusercontent.com/assets/1186326/7501488/379143ee-f402-11e4-97af-ff584dde9090.png)

Here's the svg with pupil inside the eye: https://drive.google.com/open?id=0BzfN9sXlOXt1U2hxbjlkbkh6Qnc&authuser=1

**Comment by iamjessklein** [comment]
Here's the revised back: 

![red-pupiled-eye](https://cloud.githubusercontent.com/assets/535012/7502076/583a8d94-f407-11e4-9038-0b283599c4e5.png)

**Comment by iamjessklein** [comment]
![blue-eye](https://cloud.githubusercontent.com/assets/535012/7502137/c623fc28-f407-11e4-8148-181c97015dc5.png)

![red-pupiled-eye](https://cloud.githubusercontent.com/assets/535012/7502139/c79a7910-f407-11e4-9dde-9ae3cb8ca36b.png)

**Comment by iamjessklein** [comment]
![blue-eye](https://cloud.githubusercontent.com/assets/535012/7502294/f06d1c52-f408-11e4-94b7-a1ccca219a40.png)

![red-pupiled-eye](https://cloud.githubusercontent.com/assets/535012/7502176/061e31fe-f408-11e4-88af-d087ad54feab.png)

**Comment by edrushka** [comment]
@valianttry Ready to sign off on this?

**Comment by valianttry** [comment]
hells yes! whoohooo! Let's get these files to Jean Collings asap. Can you attach them to this issue, or how should I deliver them to the engagement team?

**Comment by edrushka** [comment]
@valianttry can you paste the bug? Jess can add as attachment.

**Comment by valianttry** [comment]
oh right! Here's the bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1156362

**Comment by iamjessklein** [comment]
I've attached it on  bugzilla.

**Comment by valianttry** [comment]
@iamjessklein thanks so much for all your work on this! :clap:

**Comment by cassiemc** [comment]
Go team!
