### ISSUE TITLE
Thank you page opt-in issue

### ISSUE THREAD

**Issue by Jochai1** [MozillaFoundation/movement-building#34]
I signed the petition when using an iPhone running iOS 8.2. When I got to the thank you/opt-in to receiving future alerts from Mozilla page, I deliberately clicked on sign up now without checking the opt-in box. While the appropriate error message popped up in red, I wasn't able to actually click on the box, instead I saw a flashing cursor overlaid on top of the box.

**Comment by valianttry** [comment]
@simonwex meet @Jochai1 :smile: 
Jochai works with Chris Riley on setting policy direction and has some wicked campaigning skills. I asked him to help QA and he found a bug.

**Comment by simonwex** [comment]
:wave: Hey @Jochai1!

@edrushka, I assigned this to you, do you mind adding it to your wrangling?

**Comment by edrushka** [comment]
Confirming that this is the Surveillance petition. Also, @Jochai1, I don't suppose you got a screenshot?

**Comment by Jochai1** [comment]
It was indeed about the surveillance petition. However, I'm not able to
replicate it now, so I'd say forget about it. Sorry to have wasted folks'
time.
-Jochai

**Comment by ScottDowne** [comment]
Yeah, interesting.

I tried to replicate with no luck, I also tried to come up with a theory as to what the flashing cursor could have been. Maybe it was an OS level thing?

I'll keep my eyes open though, and feel free to reopen if you see it again :)
