### ISSUE TITLE
Padding is off around checkbox and error messages

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/movement-building#35]
This is for the buildout of #25 

![image](https://cloud.githubusercontent.com/assets/25260/7095869/d0bb01f2-df82-11e4-8f72-cc23c0e4a02f.png)

**Comment by OpenMatt** [comment]
@ScottDowne status?

**Comment by ScottDowne** [comment]
@OpenMatt Ugh, forgot about this...

**Comment by ScottDowne** [comment]
@simonwex 

Not able to reproduce or find someone else that can reproduce it.

However, a bit of padding wouldn't hurt, so I can add some anyway. (I would still like to track this down though)

Is this a blocker?

**Comment by ScottDowne** [comment]
I can reproduce with Ali's computer useing chrome on an external monitor.

Might be a chrome bug when using a retina computer with a non external monitor. @simonwex does that line up with where and how you saw it?

I'll see if I can find bug reports about that, but otherwise it's looking like this might be kinda fringy.

**Comment by ScottDowne** [comment]
Update, has nothing to do with retina, I saw it on a non retina mac, but mac+chrome+external monitor seem to be the reproducible cases from my tests. But, because it's happening on external monitors it could be pretty complex.

**Comment by simonwex** [comment]
@ScottDowne could it just be a viewport-size issue? It seems a bit strange for it to be because it's on an "external monitor".

**Comment by valianttry** [comment]
@ScottDowne and @simonwex did this get fixed?

**Comment by ScottDowne** [comment]
No, I haven't looked at it since I last updated.

I'm still leaning towards chrome bug, but would be nice to confirm/reduce it.

**Comment by ScottDowne** [comment]
Here is my thoughts.
1. Changing checkbox sizes are not something you can easily do in CSS, it's an OS thing like a page's scroll bar.
2. It's only on chrome with an external monitor with a mac.
3. it's still a usable form.
4. and my guess is most (not all) of our users are in firefox anyway.

It is for those reasons I say we don't worry about this. If any of those are proven false, that might change my mind but I'm not able to find any evidence against those points.

**Comment by valianttry** [comment]
OK by me.
