### ISSUE TITLE
Advocacy Homepage Promo Block for Sec. 215 surveillance petition

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#37]
Just flagging urgency on the homepage block, I don't see Jess on the bug yet here (I just commented there to get things moving again):
https://bugzilla.mozilla.org/show_bug.cgi?id=1152159

We have two options:
1. In the interest of time, keep the megaphone and update the copy;
2. Try out the eyeball on the homepage (I have to check with the moco folks, including Matej). I will ask on the bug if they're cool with trying the eyeball.

If eyeball is at all controversial we'll fall back to megaphone design that exists, and simply update copy (option #1).
Copy is in that bug, but i'll drop it here:
Help end mass surveillance  

or 

End mass surveillance
![we re_building_a_better_internet_ _mozilla](https://cloud.githubusercontent.com/assets/9830371/7106828/d2ac0510-e103-11e4-8e2c-471e19f2df14.png)

**Comment by OpenMatt** [comment]
- Lets just go with (1) -- it requires zero design work, and is just as good. 
- @valianttry: I'll update the bugzilla ticket.
