### ISSUE TITLE
Email callout for Sec. 215

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#38]
We need a quick update to the email callout image we used for net neutrality so we can repurpose for 215.

Net Neutrality version is here:
https://sendto.mozilla.org/page/-/2015%20Email%20CO/mozilla-advocacy_net-neutrality-february-2015_email-call-out-2.png

Needed changes:
Delete "Time is running out"
Insert: "Tell Congress to end mass surveillance"
Take Action button: no change

**Comment by OpenMatt** [comment]
Scott has the source file. Scott can you just update the copy, as per above?

**Comment by OpenMatt** [comment]
Actually Sabrina will do this

**Comment by mmmavis** [comment]
@sabrinang help! :stuck_out_tongue_closed_eyes: 
i dont remember building this in code so i assume this was an image you made

**Comment by valianttry** [comment]
@mmmavis and @sabrinang  Here's the original bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1129125

WELCOME BACK!!!  :fireworks: :scream: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile:

**Comment by edrushka** [comment]
This is needed ASAP. The email is set to go out tomorrow (April 14) at 8:00 am PST.

**Comment by mmmavis** [comment]
I _think_ @sabrinang might not be very reachable today due to traveling for work.

I'm not sure if this is the latest .ai file as she's the asset master but I did find [this](https://www.dropbox.com/s/wk07fyy1urxe7pb/mozilla-advocacy_net-neutrality-february-2015_email-call-out.ai?dl=0) in our old StudioMofo Dropbox.  Maybe we can get help from another designer if this ticket needs to be done urgently?

**Comment by edrushka** [comment]
I did this using the .ai file in the comment above. 
![mozilla-advocacy_section-215_email-callout](https://cloud.githubusercontent.com/assets/4515662/7124937/d271b85e-e1e1-11e4-9f46-da1ad8569fb7.png)

**Comment by valianttry** [comment]
@edrushka Here's the email callout for surveillance, just need the button to say "CALL NOW" for the call congress tool.

**Comment by edrushka** [comment]
Boom.
https://www.dropbox.com/s/kvmdbn6svjfujk3/mozilla-advocacy_net-neutrality-february-2015_email-call-out-04.png?dl=0
