### ISSUE TITLE
Make sure tracking is all GO for surveillance

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#39]
Adam we've been using the campaign URL builder for our tracking:
https://sendto.mozilla.org/page/s/section-215-petition

Does everything look good to go? When you have a chance, mind setting up a conversion report similar to the one we used for NN (by channel)? Thanks @adamlofting !!

**Comment by adamlofting** [comment]
@valianttry is there somewhere I can see the final tagged URLs to check the parameters are OK?

I'll get to work on that report, hopefully today.

**Comment by adamlofting** [comment]
@valianttry: 
1. The GA dashboard, by channel has been setup here:
   https://www.google.com/analytics/web/?authuser=0#dashboard/_5YjUt3IRZ6BSHsySqUeWQ/a35433268w64184110p65898710/
2. I've found an issue with the site when reviewing the analytics though. Where should I file this and which developer is working on this? Basically, the header code for the HTML has been pasted in twice so we're loading the GA script (along with a bunch of other stuff) twice and double counting views.
3. And a final request, could I please get a heads up on these projects when the design and dev work kicks off? This metrics setup doesn't have to be done at the last minute.

**Comment by valianttry** [comment]
@ScottDowne can help fix the analytics setup.
@OpenMatt @edrushka is there a "checklist of things" for project kickoff, and can we add "analytics setup" to that list? I take responsibility for this oversight, sorry for adding stress @adamlofting. :cat:

**Comment by ScottDowne** [comment]
Fixed, looks like it was a pasting error in one of the wrappers. No idea how old, but our wrapper header was duplicated in the footer, causing all sorts of nonsense.

**Comment by ScottDowne** [comment]
@adamlofting is everything good here? Can we close?

**Comment by adamlofting** [comment]
:boom:

**Comment by edrushka** [comment]
Oh, we better create another ticket for the interstitial page then. Or re-open this one?

**Comment by ScottDowne** [comment]
@edrushka new ticket

**Comment by edrushka** [comment]
Interstitial metrics ticket is here: https://github.com/MozillaFoundation/movement-building/issues/43
