### ISSUE TITLE
Add metrics to interstitial experience for Surveillance snippet campaign 

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/movement-building#43]
#### RACI:

Driver: @edrushka
Dev: @ScottDowne 
Metrics @adamlofting 
Consulted: @valianttry 
#### Milestones:

Build finalized: Wednesday April 29 EOD
QA: Thursday April 30
Snippet dates: Friday May 1 to May 15 (to be confirmed, and dependent on conversion rates)
#### Individual tickets:

Design ticket: #40
Build ticket: #41
QA ticket: https://github.com/MozillaFoundation/movement-building/issues/42

**Comment by adamlofting** [comment]
@ScottDowne once the build for this starts, can we:
1. Add [webmaker-analytics](https://github.com/mozilla/webmaker-analytics) to the code base
2. Add event tracking for in-page interactions (e.g. user answers q1, q2, etc) - like we did for the call-congress front-end pages.

Shout if you need any more detail and/or want me to look over a PR when it's ready. 

As a heads up, I'll be on PTO next week (4-8 May).

**Comment by ScottDowne** [comment]
@adamlofting 

Here is the analytics work: https://github.com/ScottDowne/surveillance-interstitial/commit/3ecf82860c3c3a82144092ba2535139a5a8de317

**Comment by ScottDowne** [comment]
@adamlofting 

Live bsd link with analytics: https://sendto.mozilla.org/page/content/surveillance-interstitial/

Could you take a look? I'm getting "[analytics] Expected `value` arg to be a Number."

Obviously I can only pass in a number, but not sure how to structure the event best. An example of the current failing event:

```
        "question chosen": {
          label: "question 1 chosen",
          value: "no"
        }
```

Let me know how you want it structured.

**Comment by adamlofting** [comment]
The `value` field is optional, so this can just be 

```
"question chosen", { label: "question 1 chosen"  }
```

**Comment by ScottDowne** [comment]
Oh, odd.

We don't are about the answer to the question?

**Comment by adamlofting** [comment]
Oh, I see that's what you mean by "no" in that example. `Value` in GA terms means a financial value or a numerical score. And I thought you were trying to say 'none'.

So in this case, let's do: 

``` JS
analytics.event("Answered Question 1", {  label: "no"  });
```

**Comment by valianttry** [comment]
@adamlofting I've asked moco if we can send a small amount of traffic to a direct "sign the petition" CTA snippet (our original concept, without interstitial). That way we can have a "control". I just need the correct tracking URL to give them to link in that standard snippet, correct? Any other considerations?

**Comment by adamlofting** [comment]
Yes, for the snippet variation that points directly to the snippet, use a different 'Referral Id / Campaign name' when [setting up the tracking URL](http://mozilla.github.io/mofo-campaignurl/). 

Then you'll be able to look at the [Landing Page report here](https://www.google.com/analytics/web/?hl=en#report/content-landing-pages/a35433268w64184110p65898710/%3F_.goalOption%3D3/) and compare conversion rates for interstitial vs direct.

For other considerations, I'm copying the note I just sent in email reply re volumes:

> The thing with statistical significance is there isn't a fixed number, until you know how different the two variations perform (which is after you start collecting data).
> 
> E.g. if skipping the interstitial was dramatically more effective (say 200%) you would have statistical significance very quickly (probably 24 hours with snippet traffic), but if it was only slightly less effective (say -0.5%) it might need to run for a few days, or have a higher % of the allocated traffic to get statistically significant results.
> 
> Playing with the numbers in this calculator can get a feel for the numbers, but the conversion rate and minimum improvement are guesses on our part before the test runs: https://vwo.com/ab-split-test-duration/
> 
> But if conversion rate is 10%, we want a 10% improvement, and a snippet can send say 15k visitors per day, if we send 30% of traffic direct to the test variation, it takes about 6 days to get statistically significant results.
> 
> Suggestions:
> If we have snippet airtime for several days, and our goal is maximum signatures, I would launch with 50% to interstitial, 50% direct to petition and as soon as there is a clear winner divert 100% of traffic to that winning variation.

**Comment by valianttry** [comment]
@adamlofting  can you double check these are good?

Tracking URLs once we confirm from Adam they're needed (I'm 99% sure they are):

1. On-interstitial page; "sign the petition" link in upper right corner:
https://sendto.mozilla.org/page/s/section-215-petition?ref=20150414Advocacy_Surveil&utm_campaign=20150414Advocacy_Surveil&utm_source=firefox&utm_medium=snippet&utm_content=Surveil215_InterstitialUPPER_R


2. On-interstitial page; "sign the petition" blue button:
https://sendto.mozilla.org/page/s/section-215-petition?ref=20150414Advocacy_Surveil&utm_campaign=20150414Advocacy_Surveil&utm_source=firefox&utm_medium=snippet&utm_content=Surveil215_InterstitialBLUEbutton

3. Link in the snippet copy (about:home):
https://sendto.mozilla.org/page/s/section-215-petition?ref=20150414Advocacy_Surveil&utm_campaign=20150414Advocacy_Surveil&utm_source=firefox&utm_medium=snippet

@ScottDowne @edrushka

**Comment by valianttry** [comment]
@edrushka @ScottDowne 

URLs for the interstitial links:
1. On-interstitial, upper right corner "sign the petition"
   https://sendto.mozilla.org/page/s/section-215-petition?ref=20150414Advocacy_Surveil&utm_campaign=20150414Advocacy_Surveil&utm_source=firefox&utm_medium=snippet&utm_content=Surveil_InterstitialUPPER_R
2. On-interstitial, bottom blue button "sign the petition":
   https://sendto.mozilla.org/page/s/section-215-petition?ref=20150414Advocacy_Surveil&utm_campaign=20150414Advocacy_Surveil&utm_source=firefox&utm_medium=snippet&utm_content=Surveil_InterstitialBLUE_button

**Comment by ScottDowne** [comment]
I think this is all done, closing.

**Comment by adamlofting** [comment]
Just for info, we don't need to use these referral parameters when linking between pages _within_ the same Google Analytics property (in this case the interstitial and the form are both on sendto.m.o).

They are most useful for exteral content that points to our pages (e.g. email, snippet, other websites).
