### ISSUE TITLE
Update Surveillance snippet eye to match interstitial experience designs

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/movement-building#44]
Right now the eye is blue.

The designs in https://github.com/MozillaFoundation/movement-building/issues/40 are moving towards a black and white eye.

This mean we probably need to update the snippet to match.

Initial work is here:

http://scottdowne.github.io/eoy-snippets/eyeball-snippet-bw-center/
http://scottdowne.github.io/eoy-snippets/eyeball-snippet-bw-outline/
http://scottdowne.github.io/eoy-snippets/eyeball-snippet-bw-nooutline/

Interstitial design ticket is here: https://github.com/MozillaFoundation/movement-building/issues/40

**Comment by cassiemc** [comment]
Hey @ScottDowne @edrushka @valianttry  this is what I had in mind as a style update, what do you think?
![surveillance-snippet](https://cloud.githubusercontent.com/assets/1186326/7372192/7281cf5c-ed93-11e4-83e1-6cbec6e996aa.png)

**Comment by edrushka** [comment]
Oh, I LOVE it!

**Comment by ScottDowne** [comment]
Works for me.

It moves right?

**Comment by cassiemc** [comment]
Yes, it moves! @ScottDowne I'd assume you need svg for the background of the eye (all but the inner circle)?

**Comment by ScottDowne** [comment]
Yeah, I can make the iris and pupil in css.

I could also move around two svgs if you want to make the iris and pupil another separate svg, whichever you feel like doing. My guess is it's as easy for me to make it in css.

**Comment by cassiemc** [comment]
@ScottDowne The background asset for the eye is here: https://www.dropbox.com/s/vi09hd4w5xpamdj/icon-eye-background-snippet.svg?dl=0 I wonder if the blink will still work with the eyelashes though so we might have to tweak / recut.

**Comment by ScottDowne** [comment]
@cassiemc yeah blink with eyelashes is going to be hard.

Also, I wonder if you could make the white part of the eye a transparent circle? That way I don't need to replicate the background colour.

**Comment by cassiemc** [comment]
@ScottDowne Yes I can do that -- but didn't you want to move the pupil around? All eye assets are now in this folder: https://www.dropbox.com/sh/tlifkldxcuqokzn/AAAp1yw-FEQFY5_wv1wHPBhxa?dl=0

**Comment by cassiemc** [comment]
Here are the eyelashes as a separate file if that helps @ScottDowne @flukeout https://www.dropbox.com/s/ltrj2wkol0w9i98/icon-eyelashes.svg?dl=0

**Comment by ScottDowne** [comment]
I am sure everyone has seen this, but just to put it somewhere, here is the staging of the new snippet eye: http://scottdowne.github.io/eoy-snippets/eyeball-snippet/

**Comment by ScottDowne** [comment]
In review, tracking is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1152133#c25

**Comment by ScottDowne** [comment]
This was done, closing.
