### ISSUE TITLE
Add link to survey at the top of the page

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#45]
We are hoping that the user's eye is drawn down and through the survey with animation and auto-sliding the page, but in case that does not work it probably makes sense to have a fallback.

@valianttry @edrushka @flukeout @ScottDowne What do you think of having a link at the top right of the page? A la:

![topnav-link](https://cloud.githubusercontent.com/assets/1186326/7379347/37a72ed4-edc2-11e4-9dc9-1cfc0696f313.png)

p.s. @edrushka did I file / label / milestone this ticket correctly?

**Comment by edrushka** [comment]
Oh, that's a really nifty solution. I have absolutely no objection to that link.
And yah, @cassiemc repo/label looks good :clap: I'll create a milestone for the Surveillance campaign since there isn't oneyet.

**Comment by cassiemc** [comment]
Ok great, then this should be ready to implement as well. The icon is font-awesome pencil: http://fortawesome.github.io/Font-Awesome/icon/pencil/
Link is in Sandstone colors, default is #0095DD and hover is #00539F, bold Open Sans (same size and font weight as the "your answer" text)

@edrushka If you think this should be part of the milestone can you assign to @ScottDowne?

**Comment by edrushka** [comment]
@valianttry, this is your call. Do you like the direct link to the petition in the upper right corner?

**Comment by valianttry** [comment]
@edrushka yes! love it. No suggested edits, either.

**Comment by ScottDowne** [comment]
This was done, closing.
