### ISSUE TITLE
QA mobile interstitial experience for Surveillance snippet campaign

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/movement-building#47]
Mobile version on staging: http://scottdowne.github.io/surveillance-interstitial/public/

**Comment by ScottDowne** [comment]
Adding full height screenshots for various states:

![screen shot 2015-05-04 at 16 51 29](https://cloud.githubusercontent.com/assets/197334/7462328/9a7a92d8-f27e-11e4-88dc-3e26a1fc1e5c.png)
![screen shot 2015-05-04 at 16 50 51](https://cloud.githubusercontent.com/assets/197334/7462329/9cd9dc78-f27e-11e4-9844-99b67dd4beb1.png)
![test](https://cloud.githubusercontent.com/assets/197334/7462330/9e8e50b2-f27e-11e4-9e6f-717000c1cd11.png)

**Comment by ScottDowne** [comment]
The top bits (mozilla logo, eye, and top link) feel not right to me.

Mostly this is just a pass at stacking the base elements.

**Comment by edrushka** [comment]
@cassiemc @valianttry please leave your QA comments here. Thanks!

**Comment by valianttry** [comment]
I just clicked on the link and the design isn't responsive on my HTC One (android).
![screenshot_2015-05-05-09-57-34](https://cloud.githubusercontent.com/assets/9830371/7478362/3257bbe0-f30f-11e4-9b18-4267c1d701da.png)

**Comment by ScottDowne** [comment]
Updates, not sure how to update redpen with a new version. Not seeing anything that looks like upload or update, so maybe I need permission to do that? Anyway, here is the screenshot at the least.

![upate](https://cloud.githubusercontent.com/assets/197334/7483430/f6efe7b0-f34c-11e4-9578-c60041af49e1.png)

**Comment by cassiemc** [comment]
@ScottDowne I added permissions to the redpen project for you and @flukeout.

@edrushka @valianttry Re. the link at the top, I think it's fine to remove it design-wise, just thinking in general that the usability of the form on mobile isn't perfect, as it's quite a long page, so a link at the top might help with conversion. I think if we could get it to fit on one line it wouldn't be so prominent.

**Comment by valianttry** [comment]
+1 I'm cool if it's just reduced in prominence... the whole point of the interstitial is not to send people direct to the petition. But I totally want it to be "available" higher than the bottom.... your job is so easy!! :smile:

**Comment by ScottDowne** [comment]
@valianttry Are you happy with the prominence on the most recent screenshot or do you think it needs to be lowed a few more notches?

**Comment by valianttry** [comment]
Where do i find a recent screenshot @ScottDowne ?

**Comment by valianttry** [comment]
Just surfed to http://scottdowne.github.io/surveillance-interstitial/public/ on my phone (please let me know if this isn't the current version I should be QAing). I still think the "stop mass surveillance. sign the petition" is way too prominent. Can we reduce font size, remove bold? Also if I'm just casually reading, it kind of says "mozilla stop mass surveillance" which is problematic. The rest of the interaction looks great (love the auto-scrolling and it flows really nicely!)

![surveillance_campaign_april_2015_-_google_drive](https://cloud.githubusercontent.com/assets/9830371/7507248/e345a8e6-f421-11e4-8e3d-3eaa790c7033.png)

**Comment by ScottDowne** [comment]
@valianttry Good to know, I'll try some more things, but if this becomes that last thing that's blocking shipping mobile, can we consider removing it and reintroducing it later in a better form?

**Comment by valianttry** [comment]
@ScottDowne I'm worried about it because the whole reason we were asked by moco to build the interstitial was to de-emphasize the assertive "sign the petition" ask... let me show this to that team and see if they're OK with it. I am anticipating some pushback but maybe not! Will do tomorrow.

**Comment by valianttry** [comment]
@ScottDowne I already have a tentative "site is fine as is" from moco... awaiting confirmation though. Just didn't want you to do any work in the interim.

**Comment by edrushka** [comment]
@cassiemc have you signed off on design here?

**Comment by valianttry** [comment]
Got this feedback from Michaela on the moco team:

_Looks good! The numbers for the questions aren't centered with the view on my iPhone. Just a flag. Petition positioning looks good._ 

So, double check #s in iOS, but the petition font / size is good to go.

**Comment by cassiemc** [comment]
@edrushka @ScottDowne I'm seeing some centering and spacing issues on iOS as well with more than just the numbers (also the illustrations, yes/no boxes, and or). Very close though! Screenshots attached.
![img_1100](https://cloud.githubusercontent.com/assets/1186326/7523558/7de5a31c-f4ca-11e4-98d0-c26ca5dcf7c9.PNG)
![img_1101](https://cloud.githubusercontent.com/assets/1186326/7523560/7deab348-f4ca-11e4-855b-927d181c8054.PNG)
![img_1102](https://cloud.githubusercontent.com/assets/1186326/7523559/7de98766-f4ca-11e4-954f-9c9480a04634.PNG)
![img_1103](https://cloud.githubusercontent.com/assets/1186326/7523561/7debd99e-f4ca-11e4-9cce-45258f752933.PNG)

**Comment by ScottDowne** [comment]
Looks like flexbox isn't working as expected in IOS.

I'm looking into it.

**Comment by ScottDowne** [comment]
@valianttry @cassiemc The flexbox stuff is fixed now.

**Comment by valianttry** [comment]
@cassiemc @erikao @ScottDowne are we good to go to prod? What's left?

**Comment by edrushka** [comment]
If the spacing issue was resolved, I think that's the last outstanding thing unless @cassiemc has further design QA.

**Comment by ScottDowne** [comment]
I'll push it to prod tomorrow morning.

Not super comfy pushing it now as I'm about to be done for the day.

**Comment by valianttry** [comment]
Hey @ScottDowne how is this coming?

**Comment by ScottDowne** [comment]
Just waiting for my meetings for the day to be over.

**Comment by ScottDowne** [comment]
Shipped

**Comment by valianttry** [comment]
WUT! 

:clap: 
:clap: 
:clap: 
:clap: JAZZ HANDS:clap: 
:clap: 
:clap: 
:clap:

**Comment by ScottDowne** [comment]
:bowtie:
