### ISSUE TITLE
Double check the email subscription setup in BSD for 215 petition 

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#48]
@edrushka Just ran a query in BSD and saw that only 35 out of 29K+ people have checked "yes" to opt in to email list (0.12%) since we launched in the snippet -- this seems very wrong. I then pulled a similar query for net neutrality and saw similar tiny #s signing up. Our optin rate for fundraising was 15% - 18%. Can we please double check that the signup form set up is correct on the back end? 

Surveillance optins:
![search_for_people___create_mailing_list](https://cloud.githubusercontent.com/assets/9830371/7485325/ba5237c6-f348-11e4-8f2c-bc665cb3b3e2.png)

Net Neutrality optins:
![search_for_people___create_mailing_list](https://cloud.githubusercontent.com/assets/9830371/7485384/c9ead250-f349-11e4-8547-508f42173500.png)

**Comment by ScottDowne** [comment]
The only check boxes I can see on either the petition page or the thank you page are the "agree with our privacy policy" checkbox.

**Comment by edrushka** [comment]
@ScottDowne can you elaborate? Does that mean the backend is working as expected?

**Comment by ScottDowne** [comment]
@edrushka Doesn't look like it expectations are on the same page. I know what it does, I'm not sure what is expected of it anymore.

Any signatures in that thank you page are essentially the "opt in" emails, the petition emails are just petition signatures and not mailing list emails. This was copying the net neutrality setup.

We can change it.

One idea is, add an "opt in" checkbox to the petition page, which would actually invalidate the thank you page, so maybe we remove it. Might increase our opt in conversion, and our share page usage.

**Comment by valianttry** [comment]
@ScottDowne I'm confused. The whole purpose of the Thank You page is an opt-in, we do not need to add a checkbox for opting in when the only action on that Thank You is to confirm your email address and opt in. If we add a checkbox on a form, then we DO need to ask people to check a box (because it's on the same page as other fields or actions required).

Can we have a quick meeting to check in on this today asap?

**Comment by ScottDowne** [comment]
@valianttry yes, let's sort this out on video asap.

**Comment by ScottDowne** [comment]
This was fixed, closing.
