### ISSUE TITLE
Stand up staging version of call-congress API

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/movement-building#5]
Code lives here:
https://github.com/mozilla/call-congress

Part of #4

**Comment by jdotpz** [comment]
So more specifically, we are just going to host the static portion of this?

**Comment by jdotpz** [comment]
cc'ing @rubbingalcoholic here
Hi rubbingalcoholic!  So we're looking to host the form rather than the backend.  Can you confirm that would be under static, or would it be elsewhere?

**Comment by simonwex** [comment]
@jdotpz we're going to host the whole thing, not just static assets.

**Comment by ScottDowne** [comment]
@jdotpz When do we expect this, and do you need help with anything?

**Comment by jdotpz** [comment]
Likely I can have it up by tomorrow at noon or so.  I'm building out the staging infra now.

**Comment by jdotpz** [comment]
Working from it here: https://github.com/MozillaFoundation/mofo-devops/issues/2

**Comment by jdotpz** [comment]
@simonwex We may need to start thinking on getting our own versions of items listed in https://github.com/mozilla/call-congress/blob/master/data/campaigns.yaml

**Comment by jdotpz** [comment]
Do we have keys for these?  @valianttry @simonwex 

The app uses environment variables to store account keys. For development you will need to set:

SUNLIGHTLABS_KEY
TWILIO_DEV_ACCOUNT_SID
TWILIO_DEV_AUTH_TOKEN
TW_NUMBER
REDISTOGO_URL (optional Redis URL for caching the Google Spreadsheet data)
and for production:

SUNLIGHTLABS_KEY
TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN
APPLICATION_ROOT (url for application server)
TASKFORCE_KEY (used for querying statistics)

**Comment by jdotpz** [comment]
Getting this on the foreman start:
/var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/process.rb:54:in `run': undefined method`spawn' for Process:Module (NoMethodError)
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/process.rb:53:in `chdir'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/process.rb:53:in`run'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:356:in `spawn_processes'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:353:in`upto'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:353:in `spawn_processes'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:352:in`each'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:352:in `spawn_processes'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:57:in`start'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/cli.rb:41:in `start'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in`**send**'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/bin/foreman:7
    from /usr/local/bin/foreman:19:in `load'
    from /usr/local/bin/foreman:19

I'll keep working at it here.

**Comment by jdotpz** [comment]
@rubbingalcoholic hi!  Can you tell me which version of python you cats are using for your servers?

**Comment by rubbingalcoholic** [comment]
Hi @jdotpz - we're using Python 2.7.3. Were you having trouble getting it to work? The method I've used is:

```
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```

Also, it helps to have all your environment variables defined in a hidden file called `.env`. Then you just do:

```
source .env
python app.py
```

And assuming you're on a publicly facing server or have the ngrok tunnel open, it should work.

One caveat--for the in-depth logging of call stats, you'll need to use the logging mechanism in fftf_leaderboard.py#log_extra_data. Two considerations here:
- You will need to hash the user's phone number to comply with Mozilla's PII requirements. This is already done in models.py (see `def hash_phone`).
- You'll also need an API key to use FFTF's logging servers to record this data (it's stored outside of the call-congress app, via an API)
- (or) you could build your own logging mechanism to show the phone numbers that each person is calling in a session

I was under the impression that FFTF would host this, but it probably wouldn't be a big deal for you to set up the logging on your end if there are any privacy concerns about sending that to a third party. Happy to discuss here or have a meeting.

**Comment by jdotpz** [comment]
@simonwex Do we have any of our keys in line so we can try to get this app running?  At the moment, I think that may be why it is dead in the water.  cc'ing @valianttry since I think she may be in control of Twilio?

**Comment by davidascher** [comment]
Getting a twilio key should be trivial.  Let me know if you need me to.

**Comment by jdotpz** [comment]
Per https://github.com/MozillaFoundation/movement-building/issues/2#issuecomment-71145518, I believe @valianttry has these keys already.  I don't want to start up a bunch of accounts, if possible.

**Comment by valianttry** [comment]
@jdotpz Just got word from our Twilio rep (Rob Spectre) he says we should create a new Twilio account and that our service is comped for this campaign as long as Twilio is acknowledged. JP do you just want to create an account and log the credentials somewhere in case others need them? I'll get more details about how we should acknowledge Twilio (they're mentioned in the privacy copy text but no logo; etc).

**Comment by davidascher** [comment]
Nice!

**Comment by valianttry** [comment]
Twilio brand mark is here: https://www.twilio.com/press (scroll down)

We should just drop it in subtly / small and low on the page. Maybe just "Special thanks to [wordmark]"

**Comment by jdotpz** [comment]
@rubbingalcoholic Where might we get a taskforce key?

**Comment by jdotpz** [comment]
@rubbingalcoholic does this look correct?
export APPLICATION_ROOT="https://callcongress.mofostaging.net"

**Comment by jdotpz** [comment]
@rubbingalcoholic Unsure if this is related, but here's what I get when we start the server:

http://pastebin.mozilla.org/8401831

ubuntu@ip-10-203-173-15:~$ curl http://localhost:5000
Internal Server Errorubuntu@ip-10-203-173-15:~$

**Comment by jdotpz** [comment]
@rubbingalcoholic Can we just setup a call to go over these things?  I'm getting a bit stuck on many bits here, so I could use a hand.

**Comment by jdotpz** [comment]
Staging version is up, puppetized, automated, on jenkins, and all that happy stuff.

**Comment by ScottDowne** [comment]
@jdotpz  Where does it live? url?

**Comment by jdotpz** [comment]
https://callcongress.mofostaging.net is the URL for staging.  The prod URL is still not decided.

**Comment by jdotpz** [comment]
Last week, we noticed that a few differences were hosing us.  I was using python app.py instead of foreman on our puppetized version, because I was having difficulties with foreman.  

https://github.com/ddollar/foreman/issues/473 has a solution for it, someone posted it two days ago(yay!).  

_BEFORE_
(callcongress)root@i-38b84ed7:/var/www/callcongress# foreman start web
/var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/process.rb:54:in `run': undefined method`spawn' for Process:Module (NoMethodError)
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/process.rb:53:in `chdir'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/process.rb:53:in`run'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:356:in `spawn_processes'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:353:in`upto'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:353:in `spawn_processes'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:352:in`each'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:352:in `spawn_processes'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/engine.rb:57:in`start'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/lib/foreman/cli.rb:41:in `start'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in`**send**'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /var/lib/gems/1.8/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /var/lib/gems/1.8/gems/foreman-0.77.0/bin/foreman:7
    from /usr/local/bin/foreman:19:in `load'
    from /usr/local/bin/foreman:19

_AFTER_
(callcongress)root@i-38b84ed7:/var/www/callcongress# service callcongress start
callcongress start/running, process 26470

The solution was to uninstall foreman, and downgrade:
gem install foreman -v 0.61

I'll get that puppetized so we start using the correct settings.

**Comment by jdotpz** [comment]
This has been completed.  Puppetization works on fresh instances, and I've confirmed the call works just as our demo instance did.
