### ISSUE TITLE
Resize eye icon for Firefox for Android snippet

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#51]
Moco needs a version of the eye icon we are using in the snippet that is 96 x 96px in png. The image should be static, non-animated.

Timeline: next 24 hours if possible to launch the surveillance snippet on Firefox for Android 

@edrushka @cassiemc

**Comment by edrushka** [comment]
@cassiemc please re-assign to Jordan if that makes more sense. I thought it might be easier for you to do since you have the context. @valianttry is there bug we should put this in, or just email to Jean?

**Comment by cassiemc** [comment]
coming right up!

**Comment by cassiemc** [comment]
Actually @valianttry @edrushka do you have an example of the context where this will be used? A screenshot would be great

**Comment by cassiemc** [comment]
Also, what resolution?

**Comment by cassiemc** [comment]
Here are some options all at 150ppi (you'll need to download them to properly preview then, as a couple options have transparent backgrounds). All are in this folder, including the source psd: https://www.dropbox.com/sh/d1i8o6m7fatqup6/AADOqtOxuxbtK5zlujZqF83sa?dl=0

![eye-grey-bkg](https://cloud.githubusercontent.com/assets/1186326/7575764/a539c5b8-f805-11e4-802d-b474838f1240.png)
![eye-grey-smaller](https://cloud.githubusercontent.com/assets/1186326/7575766/a53a7f30-f805-11e4-9370-b7d95c97ebc1.png)
![eye-grey](https://cloud.githubusercontent.com/assets/1186326/7575765/a53a35c0-f805-11e4-844d-99ccc6ef8496.png)
![eye-transparent-grey](https://cloud.githubusercontent.com/assets/1186326/7575768/a53bdbb4-f805-11e4-84fa-a0d7fe35d7a6.png)
![eye-transparent-white](https://cloud.githubusercontent.com/assets/1186326/7575767/a53b9578-f805-11e4-8707-52a56695c5e2.png)

**Comment by valianttry** [comment]
@cassiemc Jean just repeated "we just need 96x96 .png" when I asked about resolution. Here is a screenshot of where it will show on screen:

![google_drive](https://cloud.githubusercontent.com/assets/9830371/7575830/072e950a-f7ed-11e4-80e5-c0859073872a.png)

**Comment by cassiemc** [comment]
Thanks @valianttry! I imagine one of those that I posted will work great. I'm also going to put a couple svgs in that folder which would be crisp at any res, but not sure if that would render well on android. Worth a try!

Here's the final folder of assets: https://www.dropbox.com/sh/d1i8o6m7fatqup6/AADOqtOxuxbtK5zlujZqF83sa?dl=0

**Comment by valianttry** [comment]
@cassiemc the files you provided work fine. Thanks!

**Comment by cassiemc** [comment]
:hand:

**Comment by edrushka** [comment]
:purple_heart::blue_heart::yellow_heart::point_right: Thanks Cassie! :point_left::yellow_heart::blue_heart::purple_heart:
