### ISSUE TITLE
Mozilla 101 Presentation

### ISSUE THREAD

**Issue by DaveSteer** [MozillaFoundation/movement-building#56]
Developing a slide deck that serves as an introduction to Mozilla. This will be initially used for the Ford-Mozilla Open Web Fellows immersion bootcamp, but we envision multiple internal stakeholders and teams (and the community) being able to use the slides. 

This is a quick turn around project. 

cc @edrushka

**Comment by DaveSteer** [comment]
Deadline: Thursday, May 28

**Comment by lovegushwa** [comment]
@DaveSteer 
Hi Dave, I think I can help you with this. Do you have any prior examples? Also are you providing the content?
cc @edrushka

**Comment by edrushka** [comment]
Dave, just flagging that Jordan works from the States so will be off Monday. We'll need to get the content ASAP to meet the Thursday deadline. Thanks!

**Comment by cassiemc** [comment]
What's the preferred format, as well? Google docs? Powerpoint? Keynote? Indesign? I'd assume it'll need to be accessibly editable, but that'll make a big difference as to how it's designed and built out.

**Comment by DaveSteer** [comment]
Hi all -

Great! Very excited that you are helping with this, @lovegushwa.

I'm drafting the slides now. I'll have a share-able version by EOD tomorrow so that you can get started on it on Tuesday morning. I'm capturing imagery/logos/screen shots where I can, but the design will be very drafty when I send it to you. For some of the imagery, I'm hoping that we have some of the original assets (e.g. logos, photos) somewhere in the design folders.

Re: Format -- Keynote.

Re: Timeline -- I think we can push the final deadline by a few days. How about this for a revised timeline:
5/29 - 1st rev of slide deck
6/1 - feedback/comments from Dave
6/3 - final slide deck

Good with you all?

--Dave

**Comment by lovegushwa** [comment]
Hi @DaveSteer 
Sounds like a good plan! I'll let you know if if have questions once I get a copy of the early draft.

**Comment by lovegushwa** [comment]
@DaveSteer  @edrushka 
Hi Dave & Erica, you can download a proof of the Mozilla 101 deck here: http://we.tl/Pa4cYRniKY

**Comment by edrushka** [comment]
Thanks, @lovegushwa :balloon::tada::balloon::tada::balloon:

**Comment by DaveSteer** [comment]
This is so good, @lovegushwa. I'll have comments by Monday. Thank you thank you thank you.

**Comment by lovegushwa** [comment]
Hi @DaveSteer , let me know if you need any changes to meet the 6/3 deadline. I will be offsite this afternoon but can finish up any revisions tomorrow morning!

**Comment by DaveSteer** [comment]
Hi @lovegushwa - I'm meeting with the MoCo Brand team today to incorporate their feedback. I'll send that to you tonight - that delays us by a day, but I think that's OK since the changes are not too major.

Would it help you if I sent my feedback now rather than waiting to consolidate all of it? Happy to do that.

--Dave

**Comment by lovegushwa** [comment]
@DaveSteer @edrushka 
Hi Dave, please see the attached revision. Let's catch up today. I have a few questions (I need to clarify a few changes and need help identifying a few additional images.) 
http://we.tl/oBYNHGitRN

**Comment by lovegushwa** [comment]
Hi @DaveSteer @edrushka 
Please see this link to the final revised deck.
http://we.tl/Ffrd1sAHP5

**Comment by edrushka** [comment]
Very nice! Thanks, Jordan!
