### ISSUE TITLE
Personal Democracy Forum 2015 - insert

### ISSUE THREAD

**Issue by lovegushwa** [MozillaFoundation/movement-building#57]
D? @DaveSteer @sabrinang @cassiemc @edrushka 
Please review the Personal Democracy Forum 2015 - insert. Just a little background @sabrinang we were offered advertising slot in a conference publication today. It's a quick landscape revision of a similar previous insert (Provided by Dave, see bellow.) We need to move quick to make the print deadline.

![mozilla-global-open-web-proof-b](https://cloud.githubusercontent.com/assets/12228435/7872848/5329a164-0550-11e5-945b-1a69067d5720.jpg)

![screen shot 2015-05-28 at 12-1 31 41 pm](https://cloud.githubusercontent.com/assets/12228435/7872822/1b302c1a-0550-11e5-83cf-46ab7c61ef44.png)

**Comment by DaveSteer** [comment]
Two corrections:
1. The URL should be www.mozilla.org/advocacy (was missing the 'o' in advocacy)
2. Make the 'w' lower case in 'web' at the bottom (free and open web)

Thanks!

**Comment by lovegushwa** [comment]
@DaveSteer 
Got it, thanks!

**Comment by sabrinang** [comment]
A small tweak would be to try to align the wordmarks - maybe by making firefox wordmark slightly larger to align the baseline or try matching the cap height of the “F" with “mozilla" x-height but I get that the firefox logo has more visual weight so it might feel more off balance after so you can disregard.

Also, matching the right margin with the left margin so the words “resource” and “accessible” are not as close to the edge of the page.

Other than that its looking good!

**Comment by lovegushwa** [comment]
@sabrinang good feedback, thank you!
