### ISSUE TITLE
Update advocacy.mozilla.org with Maker Party promo

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/movement-building#58]
RACI

Driver: @kevzawacki
Decision Maker: @HPaulJohnson 
Design Lead: TBD
Consulted: @amirad @chrislarry33 @edrushka @valianttry @DaveSteer 

If possible, we're looking to update the advocacy.mozilla.org homepage with a banner promoting this year's Maker Party (July 15-31). 

This same banner will also live on webmaker.mozilla.org and teach.mozilla.org. Tentative/suggested banner dates: July 1 - July 31. 

Existing assets can be found here: https://github.com/mozilla/teach.webmaker.org/issues/736#

**Comment by DaveSteer** [comment]
Fascinating! As long as the messaging is advocacy oriented. Excited to dive into this.

**Comment by edrushka** [comment]
I agree the message should be advocacy oriented. That likely means tweaking the existing assets - perhaps to point to an advocacy or policy related teaching resource.

**Comment by HPaulJohnson** [comment]
We will have 3 featured activities that we are promoting as part of this year's Maker Party marketing campaign. One of those is privacy related. Would that work?

**Comment by edrushka** [comment]
Likely it could! Can we see?

**Comment by HPaulJohnson** [comment]
@amirad - can you share the privacy activity for Maker Party?

**Comment by amirad** [comment]
Sure. These are the activities we will highlight

Get a hold of your data online. Learn about cookies and third party tracking http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-lightbeam.html

Psst. No wifi at your event? Do the draw a secure password activity http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-secure-passwords.html

**Comment by edrushka** [comment]
Thanks! IMO, the first one, http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-lightbeam.html, seems like the best fit for the site's audience but I'll let @DaveSteer  or @valianttry make that call.

@HPaulJohnson did you have any ideas about tweaking the graphic assets specifically for this page?

**Comment by DaveSteer** [comment]
Gosh - I really love both of the activities. Do we have to pick one? If yes, let's go with Lightbeam. If no, would be great to be able to feature both (one for privacy; one for security).

**Comment by KevZawacki** [comment]
Some possible banner copy:

July 15-31
Participate in Mozilla's Maker Party, our global campaign to teach critical skills like Web privacy and security. Learn about tracking, cookies and more.
Host an event [link]

**Comment by KevZawacki** [comment]
Giving this ticket a bump.

Here's what the Maker Party promo banner looks like on webmaker.org, thanks to the nifty work of @sabrinang : https://goo.gl/EKyLej

@sabrinang, is it possible to repurpose the above banner for advocacy.mozilla.org and simply swap in new text/link?

I think we should promote the Lightbeam activity. Any suggested improvements to the below copy?

Hed: Join Maker Party and Learn About Online Privacy
Body: Maker Party is Mozilla's global campaign to teach critical skills like Web privacy and security. Join us from July 15 - 30 as we learn about tracking, cookies and more.
Button/link: Get started / http://mozilla.github.io/webmaker-curriculum/ProtectingYourData/session02-lightbeam.html

**Comment by edrushka** [comment]
When would you like this on the site?

**Comment by KevZawacki** [comment]
Is Wednesday, July 8 doable? It would then run until Friday, July 31.

**Comment by edrushka** [comment]
@sabrinang can you provide the design file?

**Comment by sabrinang** [comment]
You can find the assets for the promo banner (MP background tile + MP white logos) exported here: https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efkJQcEJseDlNOUlMUGNhdWwzMVFkcWp1anh6NEVZX0hMT1hiWTk5TExVWnM&usp=sharing

**Comment by edrushka** [comment]
thanks, @sabrinang! @cassiemc we should talk during the TPS call about which designer to assign to pull this together. Ali can implement.
