### ISSUE TITLE
BSD is updating our Kount integration - need new API key

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#59]
@edrushka 
From a July 13 email from Seth Reznik (our account rep at BSD):
Hi Andrea, wanted to send you a note because we're going to be updating our integration with Kount, moving away from implementation based on their RIS certificates, and towards API keys.  

To do this, we'd need you to generate API keys for your account. Doing so should be pretty simple, you'd:
1.  On the Kount dashboard go to Admin->API Keys
2.  Generate a new API key by clicking on "Create API Key" and with access to both RIS and API.
3.  Copy the new API key generated and send it along to us. 

I hope this makes sense. Please let me know if there's any issues here. 

Thanks.

**Comment by valianttry** [comment]
@edrushka Update from Seth: We need to get this done as soon as possible, no later than July 31

**Comment by edrushka** [comment]
@jbuck will evaluate

**Comment by jbuck** [comment]
Okay, this seems like something that's very quick to do (<5 mins), we just need to know what the login URL/credentials are for Kount. I don't have them, but I do know that Scott and Becky do. Lets wait until Scott is back from vacation next week and we'll do this then.

**Comment by jbuck** [comment]
nvm, @jdotpz was able to hook me up with some login credentials and I can generate the new API key.

**Comment by jbuck** [comment]
emailed to Seth & Andrea

**Comment by edrushka** [comment]
jbuck = :metal:
