### ISSUE TITLE
Do security review on call Congress tool

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/movement-building#6]

**Comment by OpenMatt** [comment]
This has been filed and is underway in Bugzilla here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1120582

**Comment by OpenMatt** [comment]
- Assigning to Andrea, as she's leading on this in bugzilla

**Comment by davidascher** [comment]
Actually I think a dev or JP is probably a better assignee given the specific task. JP will likely be chatting w/ @ygjb about it, so he gets it, but @ScottDowne probably cares too.

**Comment by valianttry** [comment]
@davidascher @ScottDowne I assume the security review happened yes?

**Comment by jdotpz** [comment]
@valianttry For posterity, we did receive security signoff from @ygjb.
