### ISSUE TITLE
German Campaign pages

### ISSUE THREAD

**Issue by shaghdoosti** [MozillaFoundation/movement-building#60]
Hey - 

We're hoping to launch a campaign in Germany around data retention in early September. The full campaign brief is below. 

https://docs.google.com/document/d/1MsGxaNUHPbgIeHdcd8Xd6s5Ez9WxzCVXtyDW3G0VyMg/edit

@edrushka @valianttry I wanted to start a conversation around resources for this campaign. Essentially what we'll need help with is: 

-A petition page 
-A share page 

Are there any other dev/design resources that are normally needed on campaigns that I may not be aware of?

**Comment by edrushka** [comment]
Great to see this campaign brief! Ops is meeting today to discuss PM-ing advocacy. I suggest the three of us meet up to discuss resourcing for this project.
@shaghdoosti do you have a more specific launch date? Is the launch tied to any kind of immovable real-world event?

**Comment by shaghdoosti** [comment]
Great - I'll setup a meeting. 

In terms of deadlines: the commission has three months to respond and that clock started in June. At the moment the deadline for the campaign would be the second week of September. (I'm talking to a partner group in Germany to confirm that the time frame is the same even thought there's holidays in between.)

**Comment by cassiemc** [comment]
@shaghdoosti @edrushka What's the status of this one? Trying to clean up milestones and this one seems long overdue.
