### ISSUE TITLE
New email callout for US encryption campaign

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/movement-building#61]
@cassiemc we have an urgent email for launch Friday or Monday about a terrible encryption law that is on the move (US-EN only). @shaghdoosti is leading the campaign charge. The email draft lives here:
https://docs.google.com/document/d/1hzZNiGIFz22zMMjBWRaHnkpgbp2_YaCPr6LY_Q1n_TA/edit

We need an updated callout box graphic for the campaign that will fit into our existing HTML email template. You can see an example callout in the attached image.

Here is a previous ticket with source files:
https://github.com/MozillaFoundation/movement-building/issues/38#issuecomment-92490585

Suggested text (to be confirmed by @shaghdoosti ):
Help us reach 100,000 signatures for strong data security
[take action]

![bsd_tools](https://cloud.githubusercontent.com/assets/9830371/10232912/48ca360e-6840-11e5-9d83-274cc8ba969c.png)

**Comment by cassiemc** [comment]
@lovegushwa Can you help tackle this?

**Comment by cassiemc** [comment]
I caught @lovegushwa on IRC and he said he was able to do this. @valianttry please keep me updated here.

**Comment by lovegushwa** [comment]
@valianttry @cassiemc @shaghdoosti 

Please check out the updated png below. 
"Help us reach 100,000 signatures for strong data security"

https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvMnhiQ2tDNDV1dzQ/view?usp=sharing

**Comment by cassiemc** [comment]
R+ for design, thanks @lovegushwa!

**Comment by cassiemc** [comment]
Assuming we can close this.
