### ISSUE TITLE
Design wireframes for new Open Web Fellows page

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#64]
Notes from our kickoff here: https://public.etherpad-mozilla.org/p/webfellowsupdate

We can use content from https://advocacy.mozilla.org/faq/ & https://advocacy.mozilla.org/benefits/

Additional content will be gathered in https://github.com/MozillaFoundation/movement-building/issues/63

**Comment by kristinashu** [comment]
@cassiemc @Melechuga @brettgaylor here are the initial wireframes: https://redpen.io/p/ds7226d960fbdeed27

We can definitely adapt it for different copy but let me know if you have any thoughts about the overall structure of the content and if we're missing any sections.

**Comment by kristinashu** [comment]
Updated the wireframes with some of the feedback and updated copy: https://redpen.io/p/ds7226d960fbdeed27

Opened https://github.com/MozillaFoundation/movement-building/issues/72 to discuss IA for the entire advocacy site.

High level content structure is pretty much done so I'm going to close this ticket and start on https://github.com/MozillaFoundation/movement-building/issues/67 were I'll add colour, icons, graphs, photos and explore more layouts. 

cc @cassiemc @brettgaylor @Melechuga
