### ISSUE TITLE
Benchmark other fellows sites

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#65]
We'd like to move the needle more towards a templated approach with all the fellows programs. We expect there to be differences but currently aren't clear on what those differences are. Let's do some interviews and design research so we can get closer to building a template that works for all three programs.

<img width="545" alt="screen shot 2016-01-05 at 10 03 49 am" src="https://cloud.githubusercontent.com/assets/1186326/12118314/c4b5f340-b393-11e5-8697-17fbf762086c.png">

**Comment by cassiemc** [comment]
Might still be some time for this to check our work against in this heartbeat. What do you think @kristinashu?

**Comment by kristinashu** [comment]
Yeah, I should be able to do this this heartbeat.

**Comment by kristinashu** [comment]
@cassiemc here's a spread sheet comparing content on the three fellowship sites https://docs.google.com/a/mozilla.com/spreadsheets/d/1c-JsTdHUSX7Z_cOxlDZ8z3rFgZOLPt9aeYKTpwK1b4c/edit?usp=sharing

**Comment by cassiemc** [comment]
This is great, thanks @kristinashu! Can you indicate in that doc the shared or exclusive IA between the sites? Wondering if there is a basic design structure for the site that would work for content across programs.

Also wondering if you have recommendations on how to make adjustments to any of these to improve usability. Would be looking at this from outsiders' perspectives who want to know more about Mozilla fellowships.

**Comment by cassiemc** [comment]
@kristinashu update? Possible to address my Qs above this heartbeat? (updating the milestone)

**Comment by kristinashu** [comment]
@cassiemc I made a few updates to the doc but I'm not too sure how in depth and how long I should spend on this? I'm guessing both science and news info is out of date and not the best info to work off of. Maybe we can talk tomorrow?

**Comment by cassiemc** [comment]
@kristinashu can you give me edit access to the doc please? I like the recommendations column a lot (the goal of my request was for you to help decide what to do next, so it's perfect :). I just have a few questions/comments. Not sure what you mean by science and news being out of date but happy to catch up today, ping me on mattermoz.

**Comment by kristinashu** [comment]
@cassiemc you should be able to edit the doc now

**Comment by kristinashu** [comment]
@cassiemc do you think we can close this ticket?

**Comment by cassiemc** [comment]
Yes, nice work, thanks @kristinashu. Filed https://github.com/MozillaFoundation/plan/issues/732 as a followup.
