### ISSUE TITLE
Figure out long-term URL structure for Fellows site

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#66]
This exercise is part information design, part practicality.

Currently, we have: 
- **https://advocacy.mozilla.org/open-web-fellows/** which lists the current cohort of fellows
- **https://advocacy.mozilla.org/** which happens to be mostly about the Open Web Fellows program.
- Then, as subpages, we have the tabs on https://advocacy.mozilla.org/host-organizations/, whose pages are styled quite differently.

Ideally in my mind we have a landing page that links to News, Science, and Open Web fellows subpages. Here's an attempt to map this out but we can maybe make it better / more usable?

![url-ia-ux-01](https://cloud.githubusercontent.com/assets/1186326/12119807/c2adfe96-b39b-11e5-8c8b-ec13fed430cb.png)

https://redpen.io/jx5db8131a9b2deea3

@kristinashu this might be helpful for your benchmarking #65 and wireframing #64. Would love your thoughts/feedback.

**Comment by cassiemc** [comment]
cc @brettgaylor @Melechuga

**Comment by cassiemc** [comment]
I think this bug is actually thinking longer term than we actually need for this update. I'm going to change the title and file a new bug to reflect that. New short-term bug is https://github.com/MozillaFoundation/movement-building/issues/69

**Comment by Melechuga** [comment]
Hi @cassiemc,
Had a quick chat with David in Vancouver (I'm here for the work) re: the URL structure, and he explained that the idea is to keep the OWF site at adv.m.o/xxx to say "look at one of the ways we do advocacy -- fellowships" and also to link from m.o/fellowships to say "look as one of the fellowship programs" as well; love it! Thanks for driving that conversation. M

**Comment by cassiemc** [comment]
sounds good @Melechuga! So to recap –

Short term: we'll keep advocacy.mozilla.org/openwebfellows (this update will replace what's currently there)
Long term: Let's build a new page – mozilla.org/fellowships OR fellowships.mozilla.org with a shared landing page that links to all fellowship programs.
