### ISSUE TITLE
Design UI for Open Web Fellows page/s

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#67]
This might be rough to try and finish by Jan 15 depending on when the wireframes #64 are done, but we will need this to build out the pages by Jan 29. cc @kristinashu @ScottDowne

**Comment by kristinashu** [comment]
@lovegushwa can you please share any files you have for the work you did on the advocacy site (site mockups and photos of the fellows)?

**Comment by lovegushwa** [comment]
@kristinashu lol your in for a treat. PSD files. You can find them here:
https://drive.google.com/a/mozilla.com/folderview?id=0B2qu3ExKWIlveXBMWXVHZDdNXzg&usp=sharing

**Comment by kristinashu** [comment]
Haha thanks @lovegushwa! Also please let me know if you have any ideas/benchmarks for color palette, style, navigation (we need to add a secondary level menu)... You too @natalieworth

**Comment by kristinashu** [comment]
Here's my first pass at design for the fellowship overview page: https://redpen.io/p/wt1d64bfb93fa6a6b8

@cassiemc @lovegushwa @ScottDowne please let me know if you have any feedback.

**Comment by kristinashu** [comment]
@Melechuga @brettgaylor here are the first couple pages of comps to give you an idea of where the design is heading: https://redpen.io/p/wt1d64bfb93fa6a6b8
Let me know if you have any thoughts or feedback.

**Comment by kristinashu** [comment]
I've updated redpen with some new comps. The structure is the same but I've played around with the design and am trying something a little bolder https://redpen.io/p/wt1d64bfb93fa6a6b8

**Comment by cassiemc** [comment]
I'm really liking the bolder direction @kristinashu. Feels less like a total rebrand too, more of an evolution of what's there.

**Comment by Melechuga** [comment]
+1 on the bolder design! There's no allegiance to the colors, so happy for those to change is desired; I do like the brighter colors, though. If evolution is preferred over rebrand, that's fine too.

**Comment by kristinashu** [comment]
Design is 98% done so I'm closing this ticket and opening a new one for prepping the files for dev https://github.com/MozillaFoundation/movement-building/issues/78
