### ISSUE TITLE
Build UI for new Open Web Fellows page/s

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#68]
Currently blocked by wireframes #64 and UI #67

**Comment by ScottDowne** [comment]
@Melechuga Do we know what we want the url structure for the 4 pages to be?

Home page is obvious: advocacy.mozilla.org

The others we have some things we can work with.

Something like:
advocacy.mozilla.org/overview
advocacy.mozilla.org/info
advocacy.mozilla.org/fellows

Or better, with a sub dir:
advocacy.mozilla.org/open-web-fellows/
advocacy.mozilla.org/open-web-fellows/info
advocacy.mozilla.org/open-web-fellows/overview
advocacy.mozilla.org/open-web-fellows/fellows

With a sub dir we need to decide which page advocacy.mozilla.org/open-web-fellows/ takes us to.

**Comment by ScottDowne** [comment]
@cassiemc @kristinashu I'm starting with headers and footers today.

**Comment by kristinashu** [comment]
Sweet! Personally I like the shortness of the first set of urls but if we go with the sub dir version advocacy.mozilla.org/open-web-fellows/ would need to go to advocacy.mozilla.org/open-web-fellows/overview

Footer should be very similar to https://goggles-mozilla-org-staging.herokuapp.com/
Can you pull the svgs from there?

Linked to it in https://github.com/MozillaFoundation/movement-building/issues/78 but here are most of the assets and style notes: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLdG9FeDVEdHFnN0E&usp=sharing

Let me know if you have any questions.

**Comment by cassiemc** [comment]
The UI for the open web fellows pages is all complete. Those can be seen here: https://redpen.io/p/wt1d64bfb93fa6a6b8
Design was completed in https://github.com/MozillaFoundation/movement-building/issues/67, prepping the design is in #78

**Comment by cassiemc** [comment]
Copy was completed in #63. It can be found here: https://docs.google.com/a/mozilla.com/document/d/16DPpk9dlB7YJyahjwA6Dk3h4bmNLjc2BmUDUr690oZg/edit?usp=sharing

**Comment by cassiemc** [comment]
@ScottDowne Is there a staging link yet? @Melechuga is keen to review content when possible

**Comment by ScottDowne** [comment]
@cassiemc yup, it's here: https://tranquil-hollows-89070.herokuapp.com/open-web-fellows/

**Comment by ScottDowne** [comment]
@Melechuga 

Still putting together the homepage, adding icons, and doing mobile views. Should be done this before end of day today.

**Comment by Melechuga** [comment]
@ScottDowne Awesome! Other than a few links that are broken (assume they're part of the fixing process) the copy in the very first paragraph/blurb is a bit off. I see now that the paragraph was broken in the copy on the Gdoc -- my bad for not catching this. Title should be "Open Web Fellows Program". Below, should say "The  Open Web Fellows program -- a collaboration between...." 

There are a couple of typos, but I figure that's just part of the process; if I should be flagging them now, let me know.

Thank you!

**Comment by Melechuga** [comment]
Also, the footer says "connext on Twitter" > "connect on Twitter"

**Comment by Melechuga** [comment]
Hi @cassiemc @ScottDowne @kristinashu Wondering what the update on this is. At the moment I'm scheduled to speak at Fosdem today and on the Project Call on Monday to announce; should I hold off? 

Thanks.

**Comment by ScottDowne** [comment]
I need to fix mobile view issues and likely any more feedback that comes in
or that I missed. I'm also not sure if we're pushing the sign up bit for
later or not. I still think Monday is a doable release.

**Comment by Melechuga** [comment]
Thanks for the update @scottdowne; very helpful. Let me know if there's
anything I can do to help.

Best,
Melissa

On Saturday, January 30, 2016, ScottDowne notifications@github.com wrote:

> I need to fix mobile view issues and likely any more feedback that comes in
> or that I missed. I'm also not sure if we're pushing the sign up bit for
> later or not. I still think Monday is a doable release.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MozillaFoundation/movement-building/issues/68#issuecomment-177253519
> .

## 

---

Melissa Romaine
Program Manager, Advocacy
Mozilla Foundation

Sent on the go.

**Comment by ScottDowne** [comment]
Small update. Mobile views had some work. I did the header footer and
overview page. Roughly half way there. About a day behind what I expected
but should be done by tomorrow.

**Comment by ScottDowne** [comment]
@Melechuga I did a bunch of fixes based on feedback.

https://tranquil-hollows-89070.herokuapp.com/open-web-fellows/

I'm looking for typos right now, but any help with that would be appreciated.

**Comment by Melechuga** [comment]
@ScottDowne Awesome, thanks! Typos I've found:
Advocacy Home Page:
- "Net Policy Blog" links to the USA Freedom subcategory; should just go to https://blog.mozilla.org/netpolicy/

Fellows Overview Page: 
- First paragraph: "...organizations to advance and protect the open Web, the goals of the Open Web Fellows programs are to:" > "organizations to advance and protect the open Web. **Specifically,** the goals of the Open Web Fellows programs are to:"
- Globe: Nairobi is missing dots that connect it to the map. (Is it possible to make the little dots darker?)

Info Page:
- First structure point: "...browse what the 2015 cohort worked on." should be linked to https://wiki.mozilla.org/Netpolicy/advocacy/openwebfellows
- Fellow Responsibilities first paragraph is missing a **T** in The
- Financial Terms is missing "Supplements listed below are yearly maximums in USD." above the supplement tables.

**Comment by ScottDowne** [comment]
@Melechuga Updated all but the Globe dotted lines, as that is in an image and not code. We'll need @kristinashu to make the changes to the image itself then I can reupload it to the site. I figure this is a change we can do post launch too? We wanted to make those image labels in code but ran out of time.

**Comment by ScottDowne** [comment]
Also, thanks!

**Comment by kristinashu** [comment]
Everything is looking great @ScottDowne! 

@Melechuga Toronto, San Fran and Nairobi are on the backside of the globe so the line can only hint at the location. Although I can make the dotted lines and visible dots darker.

We'll need to update the "Read the blog post to find out what host organizations are looking for. " link once that blog post is up. @Melechuga when is that post going live?

**Comment by kristinashu** [comment]
@ScottDowne i've updated the desktop globe in the assets folder https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLWjROWWpLdjdMeFU&usp=sharing

**Comment by Melechuga** [comment]
Re: blog post. It's not published yet (waiting for host org info), but it will be at this link: https://blog.mozilla.org/netpolicy/2016/01/25/2016-open-web-fellows-program-host-organizations. You can already link it, although the page isn't live. Thanks!

**Comment by cassiemc** [comment]
it's alive! https://advocacy.mozilla.org/open-web-fellows/fellows
@ScottDowne can we close this?

**Comment by ScottDowne** [comment]
Can we file any follow ups in this repo: https://github.com/mozilla/advocacy.mozilla.org/issues

**Comment by cassiemc** [comment]
:boom:
