### ISSUE TITLE
Figure out short-term URL for Fellows update

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#69]
It's clear that the advocacy site is predominantly currently about the Open Web Fellows program, which doesn't accurately reflect the ongoing work with our advocacy program. However, given the Encryption campaign, we won't be able to make any major updates to advocacy.mozilla.org prior to the new web fellows work launching on Jan 29.

This means we can either –
- A. create a new domain for the fellows work (what would that be? ie. fellows.mozilla.org/openwebfellows though I don't love the fellows subdomain, see #66 about broader longterm URL implications, or 
- B. use the existing advocacy.mozilla.org/openwebfellows url, which risks some confusing UX if users navigate back to advocacy.mozilla.org.

What do people think? I suspect we will have to live with this decision for a month or two while the other pages get updates. Maybe we already decided this yesterday but I want to make sure we're all on the same page.

Assigning to @brettgaylor or @Melechuga for a decision.
cc @kristinashu @ScottDowne and @valianttry – for longer-term implications for advocacy.mozilla.org

**Comment by cassiemc** [comment]
As per #66, @Melechuga and @davidascher advise that we keep **advocacy.mozilla.org/openwebfellows** (this update will replace what's currently there) for this short-term update.

@HPaulJohnson can weigh in on what might replace advocacy.mozilla.org by Jan 29, but we should file that as a separate bug.

**Comment by kristinashu** [comment]
@cassiemc so just to clarify, does this mean for the short term there will be nothing on advocacy.mozilla.org - it would redirect to advocacy.mozilla.org/openwebfellows? And then sub pages of Open Web Fellows like the blog would be advocacy.mozilla.org/openwebfellows/blog?
