### ISSUE TITLE
Finalize hosting plan (in particular domain implications)

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/movement-building#7]
Advocacy.mozilla.org is a wordpress site under mozilla.org security regime (because of cross-domain security issues).

Deploying on a non-mozilla.org domain is likely safer and hence easier to do fast.

We would need to figure out that domain, acquire it, get a cert, set it up etc.

Step 1: understand pros & cons.

/cc @simonwex @jdotpz @valianttry @DaveSteer

**Comment by valianttry** [comment]
pros: faster, less hassle
cons: (minor) could worry privacy-conscious users if they're taken to a non-mozilla domain (clear branding and links to privacy policies / contacts help, but it could be a speed bump for some)

If we can use the same domain for any future call campaigns, here are some possibilities:
mozcalls.com/org
mozcalling.com/org
mozillacalled.com/org
mozillacalls.com/org
mozillacalling.com/org
