### ISSUE TITLE
Redesign 'get involved' page on advocacy.org

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#70]
Do we want to restyle the get involved page - https://advocacy.mozilla.org/get-involved/ - to be more inline with the `webfellows` update?

cc @Melechuga @brettgaylor @HPaulJohnson @kristinashu

**Comment by Melechuga** [comment]
Definitely! Thanks for flagging @cassiemc. We need to change that content drastically; also, this page will evolve as we start growing the advocacy network and finding more channels of engagement. I'll work on content and update shortly.

**Comment by cassiemc** [comment]
Ok, cool! I've marked it as a P2 as our P1 efforts are about updating the topnav links (and getting the fellows linked subpages out of sandstone and in style with the rest of the site). 

When we do a more extensive redesign of advocacy.mozilla.org we should fill out the design brief and whole schebang and treat that as a separate exercise, but perhaps there are some small text styling or content updates we can do on this page in the meantime. 

Filed issue #71 for content updates.

cc @kristinashu @ScottDowne

**Comment by Melechuga** [comment]
Brett says "and...no." 
We'll build one if needed; for now the "get involved" page should be put to rest. Thanks!

**Comment by cassiemc** [comment]
Thanks @Melechuga! cc @ScottDowne for fyi
