### ISSUE TITLE
Design icons and illustrations for fellowship pages

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/movement-building#74]
Based on Design UI for Open Web Fellows page/s #67 

Comps with placeholder icons is in process are here: https://redpen.io/p/wt1d64bfb93fa6a6b8

We need to design icons for:
- Overview page: icons for 3 goals, globe illustration
- Info page: 1/3 of time graph icons, Travel and Events icons, Research & Equipment/Travel Allowance/Visa Assistance icons

**Comment by kristinashu** [comment]
@cassiemc do you think it's safe to start finalizing icons or should we wait for final copy? 

@natalieworth might help out with these.

**Comment by cassiemc** [comment]
@kristinashu Yes, definitely. Only thing I see changing might be color scheme, so we could focus on basic theme and shape until the design styles are finalized. Go team!

**Comment by natalieworth** [comment]
@kristinashu I should have time to do this between the encryption campaign things that are coming up. Do you know if there a milestone set for this?

**Comment by kristinashu** [comment]
Site launches Jan 29th so this milestone! Dev can use placeholder icons and then swap them out just before. Does that work for you @natalieworth? I can help out too.

**Comment by natalieworth** [comment]
@kristinashu For sure, Jan 29th milestone sounds good!

**Comment by kristinashu** [comment]
Awesome, thank you!

**Comment by kristinashu** [comment]
@natalieworth we're going to go with the polygonal style, similar to the globe. Might be tricky to get them to work at the smaller icons sizes so might need to sort of fake the polygonal style. 

I like this one (particularly the star, heart, diamond, and graduation cap):
![iphone_5s_darkfejzr2_800x600](https://cloud.githubusercontent.com/assets/1068783/12523051/2737185a-c109-11e5-8d59-ef5af5432102.png)

and maybe these:
![facegfx-vector-polygon-icon-vector](https://cloud.githubusercontent.com/assets/1068783/12523170/df14bd7e-c109-11e5-92f6-b3f43e38064b.jpg)

But do whatever you feel works best.

I've started a folder with these references and the globe .ai file: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLYjk1Q0xHbHd4SWM&usp=sharing

**Comment by cassiemc** [comment]
Cool directions

**Comment by natalieworth** [comment]
@kristinashu I've got 2 rough illustrated icons here: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0cXFaN2VqVi1rWWc/view Feel free to change colours/ style. I'll continue working on these in between the encryption campaign, but let me know if these are working or if I should try a different direction :) I haven't added texture yet, but it's something we could try for these also. Thanks!

**Comment by kristinashu** [comment]
Beautiful! I think these will work great. I'm not sure they need to be in the circles but still works for me if they are. Here's the ai file if you want to grab some colours https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLRGUzdVRCd3F2T28/view?usp=sharing

**Comment by cassiemc** [comment]
Any updates on this @natalieworth @kristinashu? It'd be good to get these finalized late today / early tomorrow if possible so @ScottDowne can throw them in.

**Comment by natalieworth** [comment]
@cassiemc @kristinashu Just working on the globe illustration now and will finish off/ fix the icon colours. Will post this afternoon.

**Comment by cassiemc** [comment]
@natalieworth Update?

**Comment by natalieworth** [comment]
@kristinashu Icons are all here for the Advocacy site: https://drive.google.com/a/mozillafoundation.org/file/d/0B20-0lpP23c0ZDdnUkZBQ282aEU/view
Altered the colours on some slightly (just shades) and added a plane to the globe (just delete if it's too much though) :) Let me know if there's any changes or better ideas for each. I've got time this morning to make updates

**Comment by kristinashu** [comment]
Awesome thanks @natalieworth these are great! I'll export them for dev now.

**Comment by kristinashu** [comment]
Icons have been exported to the dev assets folder: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLdG9FeDVEdHFnN0E&usp=sharing

cc @ScottDowne
