### ISSUE TITLE
Create content for advocacy.mozilla.org homepage

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#76]
From #73  – @KevZawacki & @HPaulJohnson to write content for homepage, we're aiming for end of week or early next week. Content types are: encryption headline & cta, email opt-in, advocacy program overview (1-3 points if possible, otherwise we can adapt design to a longer paragraph), and bullet points for the 'past campaigns' section

Wireframes so far are here: https://redpen.io/wn6adfa8290017e780

**Comment by KevZawacki** [comment]
Draft homepage content [here](https://docs.google.com/document/d/1QmABhR5O89XY_Zm_6xrTioX5_OwXKooeoJ55bAftxv4/edit), awaiting review and approval by @HPaulJohnson. 

Question for @cassiemc: I believe I'm also writing copy for the encryption microsite. Are [these](https://redpen.io/p/rv00aaeaa82563cde2) the latest wireframes? Are they final?

**Comment by cassiemc** [comment]
@KevZawacki No I don't believe those are final. @lovegushwa and @natalieworth will be able to tell you when the encryption stuff is finalized, I believe they are looking at it together EOD est.

**Comment by KevZawacki** [comment]
Thanks for the review, @HPaulJohnson. Copy updated accordingly. 

@lovegushwa and @natalieworth, let me know when I can help with microsite copy.

**Comment by cassiemc** [comment]
@KevZawacki @HPaulJohnson Are we good to close this issue? Content is more or less final? (we can file any changes as new bugs)

**Comment by HPaulJohnson** [comment]
@cassiemc - I actually just updated the encryption campaign promo copy based on some of the work we are doing on the campaign landing page. With that, we are good to close this issue.
