### ISSUE TITLE
Get logos for Host orgs

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#77]
@Melechuga has asked host orgs to deliver hi res / vector logos by Friday.

**Comment by Melechuga** [comment]
Github doesn't support .eps so putting all of the logos into this google folder as I get them: https://drive.google.com/a/mozilla.com/folderview?id=0BybHRPPm37TJRzZNMklmYUFqUDQ&usp=sharing

**Comment by Melechuga** [comment]
FYI the "Citizen Lab" is in lieu of University of Toronto (the lab is a part of the university). Thanks!

**Comment by Melechuga** [comment]
Freedom of the Press Foundation logo: https://freedom.press/sites/default/files/logo.png

**Comment by Melechuga** [comment]
@cassiemc @kristinashu @ScottDowne All logos collected! 7 of them are in the google folder, one is a link ^^

Thanks!

**Comment by kristinashu** [comment]
Awesome, thanks @Melechuga! 

All the edited logos are exported as SVGs in the assets folder for dev: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLdG9FeDVEdHFnN0E&usp=sharing

**Comment by Melechuga** [comment]
Blerg, I lied; missing one from Data & Society; will chase it down now (>.<)

**Comment by Melechuga** [comment]
Logos are all in. Thanks!
