### ISSUE TITLE
Prep Open Web Fellows assets for dev

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/movement-building#78]
Based on design in https://github.com/MozillaFoundation/movement-building/issues/67

Create drive folder with:
- [x] exported comps at scale
- [ ] svgs, image JPGs and pngs
- [x] font and colour style guide
- [x] interaction notes

**Comment by ScottDowne** [comment]
I like this process of a prep ticket to hand over assets!

**Comment by kristinashu** [comment]
Nice! I'm in the process of adding everything here: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLdG9FeDVEdHFnN0E&usp=sharing

**Comment by Melechuga** [comment]
Hi there! Not sure this is the right ticket, but the OWF narrative is now in its final form. Thanks for your patience @kristinashu @ScottDowne and @cassiemc.

https://docs.google.com/document/d/1WRLUoMaoWvG1z_ASsQ0_WJ7NYj8E2W0Aqc6dHpZlM1U/edit

**Comment by Melechuga** [comment]
The link to the application ("Apply Now" and "Apply to become a Fellow" buttons) is 

https://mozilla-foundation-2.forms.fm/2016-ford-mozilla-open-web-fellows-application

This is still in draft form, but as soon as the application goes lives the link will work. I'll have this live by Friday, Jan. 29.

**Comment by ScottDowne** [comment]
@kristinashu Question, I'm not seeing a notes file for the home page, I just see the notes files for the three webfellows pages.

**Comment by kristinashu** [comment]
@ScottDowne I haven't done notes for the advocacy home page yet because it isn't really approved. I'd hold off on building that page right now.

**Comment by ScottDowne** [comment]
k

**Comment by ScottDowne** [comment]
@kristinashu I'm currently looking for a google doc for the copy.

**Comment by ScottDowne** [comment]
Nvm, found it. It was a few comments up. I didn't know what it was until I looked close at it.

**Comment by ScottDowne** [comment]
It looks to be out of sync with the designs I see though. I'm a bit confused.

**Comment by ScottDowne** [comment]
I'm starting to see why bits are different, so far it makes sense. I think I'm good for now again.

**Comment by kristinashu** [comment]
Yeah the first paragraph had slightly different breaks but I've updated the doc and double checked the rest of the copy, it should be all the same now.

**Comment by cassiemc** [comment]
This might be redundant, but just to be super clear – 

@ScottDowne As far as content, go with what's in the content doc as @Melechuga made some updates yesterday / earlier today and it wasn't worth updating the designs for. We can put them up against the redpens during design QA if there are any discrepancies. 

@kristinashu Let's not make any more updates to the open web fellow redpens, except for the advocacy homepage still in review (as you noted!). It's often helpful to reupload a final image with some kind of notice or comment at the top that says 'no more comments please, this is the approved design. file further comments as github issues' That way we are all on the same page that we are no longer collecting redpen feedback, and it's clear which pages are final and approved.

**Comment by cassiemc** [comment]
@kristinashu Can we close this?

**Comment by kristinashu** [comment]
Yeah sure, there's just the icons left to do but we can follow that in https://github.com/MozillaFoundation/movement-building/issues/74
