### ISSUE TITLE
Design UI for advocacy home page

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/movement-building#79]
Based on comments in - Update homepage for Advocacy.org #73 

Wireframes: https://redpen.io/p/ds7226d960fbdeed27

Initial copy from Create content for advocacy.mozilla.org homepage #76: https://docs.google.com/a/mozilla.com/document/d/1QmABhR5O89XY_Zm_6xrTioX5_OwXKooeoJ55bAftxv4/edit?usp=sharing

**Comment by kristinashu** [comment]
I've added an advocacy home page comp to redpen https://redpen.io/p/wt1d64bfb93fa6a6b8

Trying the keep it simple but let me know if you have any feedback @cassiemc @natalieworth @lovegushwa

**Comment by kristinashu** [comment]
Made some updates based on everyone's feedback https://redpen.io/p/wt1d64bfb93fa6a6b8

**Comment by kristinashu** [comment]
@lovegushwa @HPaulJohnson please review the advocacy home page design today if you get the chance https://redpen.io/p/wt1d64bfb93fa6a6b8 

Is the email sign up on this home page the same as on the campaign microsite?

Jordan, let me know if you have a better idea of what the campaign will look like so we can make sure this home page banner layout will work. Are we thinking the image will change each week or stay the same for the entire campaign?

**Comment by cassiemc** [comment]
FYI, we are waiting for review on design review from @HPaulJohnson and @lovegushwa before we can hand this over to @ScottDowne for dev. Appreciate it if you guys can look soon!

**Comment by HPaulJohnson** [comment]
Overall, this looks good. 

I'm not a huge fan of the photo at the top primarily because it doesn't scream advocacy or activism to me (it's pretty passive with woman just looking at phone) and it feels out of sync with our age demographic (we typically think of our advocacy list as skewing older, as most advocacy lists do, while this has a much more youthful vibe).

**Comment by kristinashu** [comment]
Thanks @HPaulJohnson. The photo is completely placeholder until we get either a still from the video or some direction on what the campaign micro site will look like. So the photo will eventually be more reflective of the campaign.

**Comment by lovegushwa** [comment]
R+ @kristinashu this design will work well with a variety of campaign identities.
I made one redpen comment about the color that replaces the image in the signup at the bottom.

**Comment by kristinashu** [comment]
Thanks everyone! Closing.
