### ISSUE TITLE
Document schedule for building, QAing and shipping Call Congress tool

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/movement-building#8]
We need a schedule for milestones internal to the next two weeks, given the number of moving parts and the brick wall deadline.

**Comment by OpenMatt** [comment]
@davidascher : we need to assign this one.

**Comment by OpenMatt** [comment]
- **All design work complete**: Jan 30
- **Synch up, prioritize and assign PM in TPS**: Feb 2 
- **Security review complete**: x
- **All development work complete**: x
- **QA begins**: x
- **QA complete**: x  
- **Security review begins**: Jan 29
- **Security review finished**: ?
- **Ship to prod**: x
- **Mozilla campaign launches**: Feb 5
- **Tool is operational**: Feb 5 (stretch goal) 
- **Tool is operational** (drop dead): Feb 15
- **Campaign ends**: Feb 26

**Comment by OpenMatt** [comment]
@davidascher @simonwex @ScottDowne : please update above
