### ISSUE TITLE
Build new advocacy homepage

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#80]
UI is being finalized in #79 
Content is in #76

**Comment by kristinashu** [comment]
Design is approved! 

Copy: https://docs.google.com/a/mozilla.com/document/d/1QmABhR5O89XY_Zm_6xrTioX5_OwXKooeoJ55bAftxv4/edit?usp=sharing

Comp: https://redpen.io/p/wt1d64bfb93fa6a6b8

Style notes and jpgs of the 4 images are in the same folder as the fellowship assets: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLdG9FeDVEdHFnN0E&usp=sharing

The ENCRYPT banner text/image and the banner background colour are just placeholder for now.

**Comment by cassiemc** [comment]
This is done! https://advocacy.mozilla.org/
File any followup issues here: https://github.com/mozilla/advocacy.mozilla.org/issues

Nice work @ScottDowne @kristinashu @Melechuga!!
