### ISSUE TITLE
Design feedback on fellows dev site

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/movement-building#81]
Site is lookin good. Main things for me are:
- please make the secondary nav sticky
- add hover state to buttons - similar to https://mozilla-foundation-research.herokuapp.com/globalweb/

I've made screen caps of https://tranquil-hollows-89070.herokuapp.com/open-web-fellows/fellows and added them to redpen https://redpen.io/p/mf7c71306da73a93e1 
I'll add feedback comments there now but these will all be minor tweaks so feel free to wait until later to make the updates.

**Comment by ScottDowne** [comment]
Added the sticky menu and button hover states.

The sticky menu went together well, and I don't think I have any questions.

The button I guessed on a good colour for the blue text while hovering. I picked a colour the matched both places we use the button, but if it's worth it we can apply different styles for both places we use the button, each with a different blue while hovering.

**Comment by ScottDowne** [comment]
I noticed my sticky state for the nav is probably not the intended colour, I also decided the button hover states need to be different styles depending on where we use them, which is fine.

**Comment by ScottDowne** [comment]
Made some tweaks to the nav and buttons: https://tranquil-hollows-89070.herokuapp.com/open-web-fellows/

**Comment by kristinashu** [comment]
Ahhh look is perfect! Thanks! 

Just noticing that when I click on a secondary nav link when I'm part way down the page, the new page loads but I'm still part way down the page. Can clicking on a link bring a user to the top of the page?

**Comment by kristinashu** [comment]
Awesome, thank you @ScottDowne for making all the redpen updated. Everything is looking great.

Only remaining thing is spacing of the banner text on the homepage.

Here's what I see on staging:
<img width="1365" alt="screen shot 2016-01-30 at 9 14 56 am" src="https://cloud.githubusercontent.com/assets/1068783/12697206/5e9532e4-c732-11e5-92a8-d9a139712d76.png">

Did a quick mockup:
<img width="1240" alt="screen shot 2016-01-30 at 9 11 32 am" src="https://cloud.githubusercontent.com/assets/1068783/12697210/82122362-c732-11e5-95ed-15840fefd6d3.png">

For the title text, can you please move it down slightly and reduce the line height. Container width for the title and intro paragraph could also be wider (960px like the rest of the content).

**Comment by kristinashu** [comment]
Sorry I didn't include it in the style guide but could you please add a hover state to the text links? Text turns to #003e60 on hover.

**Comment by kristinashu** [comment]
Not super important, and definitely not a priority, but the 700 weight looks quite different in Safari than in Chrome and Firefox. The thicker title in Safari is closer to the comps (semi bold in Firefox does look a little too thin).

Screen cap of Firefox at the top and Safari below:
<img width="1251" alt="screen shot 2016-01-30 at 9 31 02 am" src="https://cloud.githubusercontent.com/assets/1068783/12697287/a4e2a838-c734-11e5-8319-69c6b7fc7df5.png">

**Comment by kristinashu** [comment]
@ScottDowne thanks again for making all those tweaks. I've updated redpen with these comments https://redpen.io/p/mf7c71306da73a93e1

**Comment by kristinashu** [comment]
Everything looks good to me, closing this ticket.
