### ISSUE TITLE
Where to link newsletter signup on advocacy homepage?

### ISSUE THREAD

**Issue by cassiemc** [MozillaFoundation/movement-building#82]
Hello @HPaulJohnson @valianttry @stephaniemcv – We need to know where to link the newsletter signup on the [bottom of the Advocacy homepage](https://redpen.io/xp34e81e49b8c80fbe). Hoping to get this and the new Open Web Fellows site live on Monday.

Is there a newsletter that is separate from the encryption campaign (that is possibly more generic), or should these point to the same place? What's the link?

cc @ScottDowne

**Comment by kristinashu** [comment]
I'm pretty sure both the advocacy homepage sign up and the campaign micro site sign up are for a general MoFo newsletter. True?

Noticing the encryption campaign https://redpen.io/p/yk6b656ce94eb032d4 asks for a name and country in addition to email address. Should we collect this info on the advocacy home page as well? 

Would it be ok to add this sign up post launch? It's not on the current site so we're not loosing anything.

**Comment by cassiemc** [comment]
@valianttry @stephaniemcv If you guys have insight here would appreciate it!

**Comment by stephaniemcv** [comment]
I think we should collect this info on the advocacy home page as well. I think it's fine to add after launch. 

I will try to find you the correct info for the signup.

**Comment by cassiemc** [comment]
Updating the milestone. Let's not forget to do this for the encryption campaign launch. cc @OpenMatt

**Comment by stephaniemcv** [comment]
@cassiemc  There is not a separate newsletter, everything is flowing into the Foundation list. There's also no specific link. The Devs have to code the landing page to point at Basket. Scott knows how and did this for the Encryption Campaign snippet.

**Comment by ScottDowne** [comment]
Ali and Alan know how too.

**Comment by cassiemc** [comment]
Ok, thanks! 

@ScottDowne @alicoding @kristinashu Do you know if adding the newsletter to the advocacy homepage is accounted for in any upcoming tickets? Ideally the advocacy homepage was intended to launch with that signup form, but if we can bundle with any encryption campaign updates that's fine.

**Comment by alicoding** [comment]
I only have seen the banner which links to the encryption campaign, but not the actual signup form. http://tranquil-hollows-89070.herokuapp.com/

I don't have any information about when or where is the ticket for that?

**Comment by cassiemc** [comment]
@kristinashu can you file a new one with assets?

**Comment by kristinashu** [comment]
There's a ticket here https://github.com/mozilla/advocacy.mozilla.org/issues/49
