### ISSUE TITLE
Complete dev work on Call Congress tool

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/movement-building#9]
WIP: http://scottdowne.github.io/call-congress-net-neutrality/call-congress.html

To do:
- [x] create and setup repo
- [x] first page HTML and CSS mobile
- [x] first page countdown 
- [x] fix broken links and add phone icon
- [x] second page HTML and CSS mobile
- [x] connect with call-congress service
- [x] interaction to navigate between page 1 and 2
- [x] input dialog error message
- [x] add waiting spinner
- [x] first page HTML and CSS desktop
- [x] second page HTML and CSS desktop

P2 tasks (report back button in page two won't be there initially):
- [x] add little triangle speech bubble thingy to call script
- [x] report back page HTML and CSS mobile
- [x] report back button, interaction and navigate between page 2 and report back
- [x] interaction to navigate between report back and thank you
- [ ] thank you page HTML and CSS mobile
- [ ] thank you page share buttons
- [ ] transitions between all page changes
- [x] report back page HTML and CSS desktop
- [ ] thank you page HTML and CSS desktop

**Comment by ScottDowne** [comment]
@OpenMatt thanks for splitting this up, much better :)

**Comment by ScottDowne** [comment]
http://scottdowne.github.io/call-congress-net-neutrality/call-congress.html
http://scottdowne.github.io/call-congress-net-neutrality/call-congress-2.html
http://scottdowne.github.io/call-congress-net-neutrality/call-congress-3.html

Still WIP, but all three states for the P1 pages are done.

**Comment by ScottDowne** [comment]
I took a quick pass, lateral slice to getting desktop views for the p1 pages. There are obvious, less important things that got left behind, but I wanted it working so we can iterate.

http://scottdowne.github.io/call-congress-net-neutrality/call-congress.html
^^ is up to date and should work.

Found issues should be noted in this issue for the time being.

**Comment by ScottDowne** [comment]
Finished. https://call.mozilla.org
